In [4]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\sruthi saji nair\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (0.10.3)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (2022.12.7)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: trio~=0.17 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (0.22.2)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.2)
Requirement already satisfied: outcome in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sniffio in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: cffi>=1.14 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [5]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
import requests
from selenium.common.exceptions import NoSuchElementException

# Q1. Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.                                                                                                                                                #Q2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name. Details to be scraped are: "Brand Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and “Product URL”.
In case, if any of the details are missing for any of the product then replace it by “-“.

In [15]:
driver = webdriver.Chrome()
driver.get("https://www.amazon.in/")

Product_input = driver.find_element(By.ID,"twotabsearchtextbox")
product_name=input("Enter the Product name you want to search for : ")
Product_input.send_keys(product_name)
Submit_btn = driver.find_element(By.XPATH,"//input[@type='submit']")
Submit_btn.click()

Product_URL = []
URL = driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')

for i in URL:
    Product_URL.append(i.get_attribute("href"))
len(Product_URL)

BrandName =[]
NameOfProduct=[]
Price=[]
Return=[]
ExpectedDelivery=[]
Availability=[]

for i in Product_URL:
    driver.get(i)
    time.sleep(6)
    try:
        Brand = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[5]/div[3]/div[4]/div[46]/div/table/tbody/tr[1]/td[2]/span')
        BrandName.append(Brand.text)
    except NoSuchElementException:
        BrandName.append('-')
    
    try:
        name = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[5]/div[3]/div[4]/div[1]/div/h1/span')
        NameOfProduct.append(name.text)
    except NoSuchElementException:
        NameOfProduct.append('-')
        
    try:
        price = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[5]/div[3]/div[1]/div[3]/div/div[1]/div/div/div/form/div/div/div/div/div[2]/div[1]/div/span[1]/span[2]/span[2]')
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('-')
        
    try:
        ret = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[5]/div[3]/div[4]/div[24]/div[2]/div/div/div/div[2]/div/ol/li[3]/div/span/div[2]/span')
        Return.append(ret.text)
    except NoSuchElementException:
        Return.append('-')
        
    try:
        Exp = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[5]/div[3]/div[1]/div[3]/div/div[1]/div/div/div/form/div/div/div/div/div[3]/div/div[2]/div[9]/div[1]/div/div/div/span/span')
        ExpectedDelivery.append(Exp.text)
    except NoSuchElementException:
        ExpectedDelivery.append('-')
        
    try:
        avail = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[5]/div[3]/div[1]/div[3]/div/div[1]/div/div/div/form/div/div/div/div/div[3]/div/div[4]/div/div[1]/span')
        Availability.append(avail.text)
    except NoSuchElementException:
        Availability.append('-')

df = pd.DataFrame({'Brand Name': BrandName, 'Name Of Product': NameOfProduct,'Price': Price, 'Return/Replacement': Return,'Expected Delivery': ExpectedDelivery, 'Availability ': Availability, 'Product URL':Product_URL})
df

Enter the Product name you want to search for : guitar

,Brand Name,Name Of Product,Price,Return/Replacement,Expected Delivery,Availability,Product URL
0,Medellin,Medellin Acoustic Guitar (with guitar learning...,"2,499",7 days Replacement,"Saturday, 12 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,Kadence,Kadence A281 Professional Acoustic Rosewood gu...,"6,499",7 days Replacement,"Saturday, 12 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Kadence,"Kadence rosewood Guitar Frontier Series, Elect...","4,999",7 days Replacement,"Saturday, 12 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Medellin,Medellin Acoustic Guitar (with guitar learning...,"2,499",7 days Replacement,"Saturday, 12 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,JUAREZ,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...","1,799",7 days Replacement,"Thursday, 10 August",In stock,https://www.amazon.in/Juarez-Acoustic-Cutaway-...
...,...,...,...,...,...,...,...
57,-,-,-,-,-,-,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
58,Henrix,Henrix 38C 38 Inch Cutaway Acoustic Guitar Wit...,"2,939",7 days Replacement,"Wednesday, 9 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
59,NM Signature,NM Signature Electra Blue Rosewood Fretboard A...,"3,789",7 days Returnable,-,Only 2 left in stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
60,Intern,Intern INT-38C-NT-G 38 Incheses lindenwood Rig...,"2,139",7 days Replacement,"Thursday, 10 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
61,Kadence,"Kadence Guitar Acoustica Series, Electric Acou...","6,999",7 days Replacement,"Saturday, 12 August",In stock,https://aax-eu.amazon.in/x/c/RDDkv9dUf2D0pgQU0...

# Q3. Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [35]:
driver = webdriver.Chrome()
Img_URL="https://www.google.com/imghp?hl=en&tab=ri&authuser=0&ogbl"
driver.get(Img_URL)
List =['fruits','cars','Machine Learning','Guitar','Cakes']

        
for k in List:
    name = k
    print(name)
    global Img_URL
    count = k + str(1)
    driver.get("https://www.google.com/imghp?hl=en&tab=ri&authuser=0&ogbl")
    time.sleep(3)
    Search_IMG = driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
    Search_IMG.send_keys(name)
    time.sleep(5)
    Search_btn = driver.find_element(By.XPATH,'//button[@class="Tg7LZd"]')
    Search_btn.click()
    time.sleep(5)
    Images = driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')
    time.sleep(5)
    Img_URL = []
    Img_data = []
    for i in Images:
        src = i.get_attribute('src')
        if src is not None:
            if(src[0:4]=='http'):
                Img_URL.append(src)
        for _ in range(2):
            driver.execute_script("window.scrollBy(0,1000)")
            time.sleep(3)
    
    for j in range(len(Img_URL)):
        if j>10:
            break;
        print("Downloading {0} of {1} images" .format(j,10))
        response = requests.get(Img_URL[j])
        file = open(r"C:\Users\Sruthi Saji Nair\Desktop\DT\Internship"+str(j)+".jpg","wb")
        file.write(response.content)

fruits
Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images
cars
Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images
Machine Learning
Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images
Guitar
Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images
Cakes
Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

# Q4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [4]:
import re
driver = webdriver.Chrome()
driver.get("https://www.flipkart.com/")

time.sleep(5)

try:
    driver.find_element(By.XPATH,'//button[@class="_2KpZ6l _2doB4z"]').click()
except:
    print("No pop-up-1")

Product_input = driver.find_element(By.CLASS_NAME,"_3704LK")
product_name=input("Enter the Product name you want to search for : ")
Product_input.send_keys(product_name)

Search = driver.find_element(By.XPATH,'//button[@class="L0Z3Pu"]')
Search.click()




BrandName =[]
SmartPhoneName=[]
Color=[]
RAM=[]
Storage=[]
PrimaryCamera=[]
SecondaryCamera=[]
DisplaySize=[]
BatteryCapacity=[]
Price=[]
Product_URL = []


time.sleep(6)

Brand = driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for i in Brand:
    try:
        BrandName.append(i.text[0:12])
    except NoSuchElementException:
        BrandName.append('-')
    
name = driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for i in name:
    try:
        SmartPhoneName.append(i.text)
    except NoSuchElementException:
        SmartPhoneName.append('-')
        
price = driver.find_elements(By.XPATH,'//div[@class="_30jeq3 _1_WHN1"]')
for i in price:
    try:
        Price.append(i.text)
    except NoSuchElementException:
        Price.append('-')
        
col = driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for i in col:
    try:
        string=re.findall(r'\((.*?)\,',i.text)
        Color.append(string[0])
    except NoSuchElementException:
        Color.append('-')
        
ram = driver.find_elements(By.XPATH,'//ul[@class="_1xgFaf"]')
for i in ram:
    try:
        RAM.append(i.text[0:9])
    except NoSuchElementException:
        RAM.append('-')
        
avail = driver.find_elements(By.XPATH,'//ul[@class="_1xgFaf"]')
for i in avail:
    try:
        Storage.append(i.text[11:17])
    except NoSuchElementException:
        Storage.append('-')
    
PC = driver.find_elements(By.XPATH,'//ul[@class="_1xgFaf"]')
for i in PC:
    try:
        string = i.text.splitlines()[2]
        PrimaryCamera.append(string.split("|"))
        SecondaryCamera.append(string.split("|")[0])
    except NoSuchElementException:
        PrimaryCamera.append('-')
        SecondaryCamera.append('-')

    
DS = driver.find_elements(By.XPATH,'//ul[@class="_1xgFaf"]')
for i in DS:
    try:
        DisplaySize.append(i.text.splitlines()[1])
    except NoSuchElementException:
        DisplaySize.append('-')
        
BC = driver.find_elements(By.XPATH,'//ul[@class="_1xgFaf"]')
for i in BC:
    try:
        BatteryCapacity.append(i.text.splitlines()[3])
    except NoSuchElementException:
        BatteryCapacity.append('-')
        
URL = driver.find_elements(By.XPATH,'//a[@class="_1fQZEK"]')
for i in URL:
    try:
        Product_URL.append(i.get_attribute("href"))
    except NoSuchElementException:
        Product_URL.append('-')
    
    

df = pd.DataFrame({'Brand Name': BrandName, 'Smart Phone Name': SmartPhoneName,'Price': Price, 'Color': Color,'RAM': RAM, 'Storage ': Storage,'Primary Camera': PrimaryCamera,'Secondary Camera': SecondaryCamera,'Display Size': DisplaySize, 'Battery Capacity': BatteryCapacity,'Product_URL ': Product_URL})
df

Enter the Product name you want to search for : Oneplus Nord

,Brand Name,Smart Phone Name,Price,Color,RAM,Storage,Primary Camera,Secondary Camera,Display Size,Battery Capacity,Product_URL
0,OnePlus Nord,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)","₹17,794",Blue Tide,6 GB RAM,128 GB,"[64MP Rear Camera , 16MP Front Camera]",64MP Rear Camera,16.74 cm (6.59 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-lit...
1,OnePlus Nord,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)","₹17,682",Black Dusk,6 GB RAM,128 GB,"[64MP Rear Camera , 16MP Front Camera]",64MP Rear Camera,16.74 cm (6.59 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-2-lit...
2,OnePlus Nord,"OnePlus Nord 3 5G (Misty Green, 256 GB)","₹37,456",Misty Green,16 GB RAM,256 G,[50MP Rear Camera],50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-3-5g-mis...
3,OnePlus Nord,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)","₹28,295",Jade Fog,8 GB RAM,128 GB,"[50MP Rear Camera , 32MP Front Camera]",50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-ja...
4,OnePlus Nord,"OnePlus Nord 3 5G (Tempest Gray, 256 GB)","₹37,149",Tempest Gray,16 GB RAM,256 G,[50MP Rear Camera],50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-3-5g-tem...
5,OnePlus Nord,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)","₹28,999",Gray Shadow,8 GB RAM,128 GB,[50MP Rear Camera],50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-gr...
6,OnePlus Nord,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)","₹27,999",Jade Fog,8 GB RAM,128 GB,[50MP Rear Camera],50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-ja...
7,OnePlus Nord,"OnePlus Nord 2 5G (Blue Haze, 128 GB)","₹26,990",Blue Haze,6 GB RAM,128 GB,[50MP Rear Camera],50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-blu...
8,OnePlus Nord,"OnePlus Nord 2 5G (Blue Haze, 256 GB)","₹34,990",Blue Haze,12 GB RAM,256 G,[50MP Rear Camera],50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-blu...
9,OnePlus Nord,"OnePlus Nord 3 5G (Misty Green, 128 GB)","₹32,854",Misty Green,8 GB RAM,128 GB,[50MP Rear Camera],50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-3-5g-mis...
10,OnePlus Nord,"OnePlus Nord 3 5G (Tempest Gray, 128 GB)","₹32,742",Tempest Gray,8 GB RAM,128 GB,[50MP Rear Camera],50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-3-5g-tem...
11,OnePlus Nord,"OnePlus Nord (Gray Onyx, 64 GB)","₹23,990",Gray Onyx,6 GB RAM,64 GB,"[48MP + 8MP , 32MP + 8MP Dual Front Camera]",48MP + 8MP,16.36 cm (6.44 inch) Full HD+ Display,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-gray-ony...
12,OnePlus Nord,"OnePlus Nord 2 5G (Green Wood, 256 GB)","₹34,990",Green Wood,12 GB RAM,256 G,[50MP Rear Camera],50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-gre...
13,OnePlus Nord,"OnePlus Nord 2 5G (PAC-MAN, 256 GB)","₹34,990",PAC-MAN,12 GB RAM,256 G,[50MP Rear Camera],50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2-5g-pac...
14,OnePlus Nord,"OnePlus Nord 2T 5G (Jade Fog, 256 GB)","₹33,990",Jade Fog,12 GB RAM,256 G,[50MP Rear Camera],50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-ja...
15,OnePlus Nord,"OnePlus Nord CE 5G (Blue Void, 128 GB)","₹24,499",Blue Void,8 GB RAM,128 GB,[64MP Rear Camera],64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-5g-bl...
16,OnePlus Nord,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)","₹28,988",Gray Shadow,8 GB RAM,128 GB,[50MP Rear Camera],50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-gr...
17,OnePlus Nord,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)","₹27,930",Gray Shadow,8 GB RAM,128 GB,"[50MP Rear Camera , 32MP Front Camera]",50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh Battery,https://www.flipkart.com/oneplus-nord-2t-5g-gr...
18,OnePlus Nord,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...","₹17,890",Chromatic Gray,8 GB RAM,128 GB,[108MP Rear Camera],108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-3-lit...
19,OnePlus Nord,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...","₹21,249",Chromatic Gray,8 GB RAM,256 GB,[108MP Rear Camera],108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-3-lit...
20,OnePlus Nord,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)","₹18,999",Pastel Lime,8 GB RAM,128 GB,[108MP Rear Camera],108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-3-lit...
21,OnePlus Nord,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB)","₹21,499",Pastel Lime,8 GB RAM,256 GB,[108MP Rear Camera],108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,https://www.flipkart.com/oneplus-nord-ce-3-lit...
22,OnePlus Nord,"OnePlus Nord (Gray Onyx, 128 GB)","₹24,990",Gray Onyx,8 GB RAM,128 GB,"[48MP + 8MP , 32MP + 8MP Dual Front Camera]",48MP + 8MP,16.36 cm (6.44 inch) Full HD+ Display,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-gray-ony...
23,OnePlus Nord,"OnePlus Nord (Gray Ash, 256 GB)","₹22,999",Gray Ash,12 GB RAM,256 G,"[48MP + 48MP + 8MP , 32MP Front Camera]",48MP + 48MP + 8MP,16.36 cm (6.44 inch) Full HD+ Display,4115 mAh Battery,https://www.flipkart.com/oneplus-nord-gray-ash...

# Q5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [10]:
import re
driver = webdriver.Chrome()
driver.get("https://www.google.com/maps/")

UserInput=input("Enter the City name : ")
Search=driver.find_element(By.XPATH,'//input[@id="searchboxinput"]')
Search.send_keys(UserInput)

Search = driver.find_element(By.XPATH,'//button[@id="searchbox-searchbutton"]')
Search.click()

time.sleep(4)

Lat = []
Long = []
try:
    Current_URL = driver.current_url
    Lat_Long = re.findall(r'@(.*)data',Current_URL)
    if len(Lat_Long):
        lat_long = Lat_Long[0].split(",")
        if len(lat_long)>=2:
            Lat.append(lat_long[0])
            Long.append(lat_long[1])
except Exception as e:
    print("Error : ", str(e))

time.sleep(2)

df = pd.DataFrame({'City': UserInput, 'Latitude': Lat, 'Longitude': Long})
df

Enter the City name : Nashik

     City    Latitude   Longitude
0  Nashik  19.9908869  73.6386599

# Q6. Write a program to scrap all the available details of best gaming laptops from digit.in.

In [13]:
driver = webdriver.Chrome()
driver.get("https://www.digit.in/")

time.sleep(2)

Laptop = driver.find_element(By.XPATH,"/html/body/div[2]/div/ul/li[2]")
Laptop.click()

time.sleep(2)

Best = driver.find_element(By.XPATH,"/html/body/div[2]/div/ul/li[2]/div[2]/div/div[1]/span[4]")
Best.click()

time.sleep(2)

Gaming_Laptop = driver.find_element(By.XPATH,"/html/body/div[2]/div/ul/li[2]/div[2]/div/div[5]/div/div[2]/a/div")
Gaming_Laptop.click()

time.sleep(2)

LaptopName=[]
Processor=[]
Display=[]
OS=[]
Memory=[]
GraphicsProcessor=[]
Body=[]
Price=[]

name = driver.find_elements(By.XPATH,'//span[@class="datahreflink"]')
for i in name:
    try:
        LaptopName.append(i.text)
    except NoSuchElementException:
        LaptopName.append('-')

Specifications = driver.find_elements(By.XPATH,'//div[@class="Spcs-details"]')
for i in Specifications:
    LaptopSpec = i.text
    laptop=LaptopSpec.replace("Processor : ","").replace("Display : ","").replace("OS : ","").replace("Memory : ","").replace("Graphics Processor : ","").replace("Body : ","").replace("Price : ","").split("\n")
    try:
        Processor.append(laptop[1])
    except NoSuchElementException:
        Processor.append('-')
    
    try:
        Display.append(laptop[2])
    except NoSuchElementException:
        Display.append('-')
    
    try:
        OS.append(laptop[3])
    except NoSuchElementException:
        OS.append('-')
      
    try:
        Memory.append(laptop[4])
    except NoSuchElementException:
        Memory.append('-')
    
    try:
        GraphicsProcessor.append(laptop[5])
    except NoSuchElementException:
        GraphicsProcessor.append('-')
    
    try:
        Body.append(laptop[6])
    except NoSuchElementException:
        Body.append('-')
        
    try:
        Price.append(laptop[7])
    except NoSuchElementException:
        Price.append('-')

LaptopName.pop()
LaptopName.pop()

df = pd.DataFrame({'Laptop Name': LaptopName,'Processor': Processor,'Display': Display,'OS':OS,'Memory': Memory,'GraphicsProcessor':GraphicsProcessor ,'Body': Body,'Price':Price})
df

,Laptop Name,Processor,Display,OS,Memory,GraphicsProcessor,Body,Price
0,HP OMEN 17 (2023),13th Gen Intel Core i7-13700HX 16 core process...,"17.3″ (2560 x 1440) screen, 165 Hz refresh rate",Windows 11 Home,16 GB DDR5GB RAM & 1 TB SSD,Graphics 12 GB DDR6 NVIDIA GeForce RTX 4080 Gr...,397.1 x 262 x 27 mm dimension & 2.78 kg weight,"₹ 269,777"
1,MSI Titan GT77 12UHS,12th Gen Intel Core i9-12900HX 16 core process...,"17.3″ (3840 x 2160) screen, 120 Hz refresh rate",Windows 11 Home,64 GB DDR5GB RAM & 2 TB SSD,Graphics 16 GB DDR6 NVIDIA GeForce RTX 3080Ti ...,397 x 330 x 23 mm dimension & 3.3 kg weight,"₹ 499,990"
2,Lenovo Legion 5i Pro,12th Gen Intel Core i7-12700H 14 core processo...,16″ (2560 x 1600) screen,Windows 11 Home,32 GB DDR5GB RAM & 1 TB SSD,Graphics NVIDIA GeForce RTX 3070 Ti Graphics card,359.9 x 264.4 x 19.9 mm dimension & 3.6 kg weight,"₹ 179,990"
3,ASUS ROG Strix Scar 18 2023,13th Gen Intel Core i9-13980HX 24 core process...,"18″ (1920 x 1200) screen, 165 Hz refresh rate",Windows 11 Home,32 GB DDR5GB RAM & 1 TB SSD,Graphics 12 GB DDR6 NVIDIA GeForce RTX 4080 Gr...,294 x 399 x 23 mm dimension & 3.1 kg weight,"₹ 279,990"
4,Acer Predator Helios Neo 16,13th Gen Intel Core i7-13700HX processor,"16″ (2560 x 1600) screen, 165 Hz refresh rate",Windows 11 Home,16 GB DDR5GB RAM & 1 TB SSD,Graphics 8 GB DDR6 NVIDIA GeForce RTX 4060 Gra...,360 x 279 x 28 mm dimension & 2.6 kg weight,"₹ 149,990"
5,ASUS ROG Zephyrus G14,AMD Ryzen 9-6900HS 8 core processor with 4.9 G...,"14″ (1920 x 1200) screen, 144 Hz refresh rate",Windows 11 Home,16 GB DDR5GB RAM & 1 TB SSD,Graphics 8 GB DDR6 AMD Radeon RX 6700S Graphic...,312 x 227 x 19 mm dimension & 1.65 kg weight,"₹ 156,990"
6,MSI Cyborg 15,12th Gen Intel Core i7-12650H 10 core processo...,"15.6″ (1920 x 1080) screen, 144 Hz refresh rate",Windows 11 Home,16 GB DDR5GB RAM & 1 TB SSD,Graphics 8 GB DDR6 NVIDIA GeForce RTX 4060 Gra...,& 1.98 kg weight,"₹ 125,000"

# Q7. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: 
“Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [13]:
driver = webdriver.Chrome()
driver.get("https://www.forbes.com/?sh=1b4d54472254")
time.sleep(2)
try:
    Menu = driver.find_element(By.XPATH,'//div[@class="_69hVhdY4"]')
    Menu.click()
    time.sleep(2)

    Billionaires = driver.find_element(By.XPATH,'//li[@class="TjJgrPSg cD45ib6e primary"]')
    Billionaires.click()
    time.sleep(2)

    World_Billionaires = driver.find_element(By.XPATH,'//li[@class="TjJgrPSg _2bNo56RE secondary"]')
    World_Billionaires.click()
    time.sleep(2)
except NoSuchElementException:
    driver.get("https://www.forbes.com/billionaires/")
    
time.sleep(2)
Rank=[]
Name=[]
NetWorth=[]
Age=[]
Citizenship=[]
Source=[]
Industry=[]

time.sleep(2)
for i in range(0,2):
    time.sleep(2)
    ranks=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[1]')
    
    try:
        for i in ranks:
            rank=i.text
            Rank.append(rank)
    except NoSuchElementException:
        Rank.append("-")
    
    names=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[2]')
    try:
        for i in names:
            Names=i.text
            Name.append(Names)
    except NoSuchElementException:
        Name.append("-")
        
    networth=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[3]')
    try:
        for i in networth:
            Networth=i.text
            NetWorth.append(Networth)
    except NoSuchElementException:
        NetWorth.append("-")
    
    ages=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[4]')
    try:
        for i in ages:
            age=i.text
            Age.append(age)
    except NoSuchElementException:
        Age.append("-")
    
    citizenships=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[5]')
    try:
        for i in citizenships:
            citizenship=i.text
            Citizenship.append(citizenship)
    except NoSuchElementException:
        Citizenship.append("-")
    
    sources=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[6]')
    try:
        for i in sources:
            source=i.text
            Source.append(source)
    except NoSuchElementException:
        Source.append("-")
        
    industries=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[7]')
    try:
        for i in industries:
            industries=i.text
            Industry.append(industries)
    except NoSuchElementException:
        Industry.append("-")
print(len(Rank))
print(len(Name))
print(len(NetWorth))
print(len(Age))
print(len(Citizenship))
print(len(Source))
print(len(Industry))

df=pd.DataFrame({'Rank':Rank,'Name':Name,'Net Worth':NetWorth,'Age':Age,'Citizenship':Citizenship,'Source':Source,'Industry':Industry})
df

199
199
199
199
199
199
199
['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '17', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '31', '33', '34', '35', '35', '37', '38', '39', '40', '41', '41', '43', '43', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '65', '67', '68', '69', '70', '71', '72', '72', '74', '74', '76', '77', '77', '79', '80', '81', '82', '83', '84', '84', '86', '86', '88', '89', '89', '89', '92', '93', '94', '94', '94', '97', '97', '99', '100', '101', '101', '103', '104', '104', '106', '107', '108', '108', '108', '108', '112', '113', '114', '115', '116', '116', '118', '119', '120', '121', '122', '123', '124', '124', '126', '127', '128', '128', '130', '130', '130', '133', '133', '133', '136', '137', '138', '138', '140', '141', '142', '142', '144', '145', '146', '147', '148', '148', '148', '151', '151', '153', '153', '153', '153', '157', '157', '159', '159', '161', '161', '161', '164', '165', '165', '167', '167', '167', '170', '171', '171', '171', '171', '171', '171', '171', '171', '179', '179', '179', '182', '183', '184', '184', '184', '184', '184', '184', '190', '190', '190', '190', '190', '195', '195', '195', '195', '195', '195']
['Elon Musk', 'Jeff Bezos', 'Larry Ellison', 'Warren Buffett', 'Bill Gates', 'Michael Bloomberg', 'Carlos Slim Helu & family', 'Mukesh Ambani', 'Steve Ballmer', 'Francoise Bettencourt Meyers & family', 'Larry Page', 'Amancio Ortega', 'Sergey Brin', 'Zhong Shanshan', 'Mark Zuckerberg', 'Charles Koch', 'Julia Koch & family', 'Jim Walton', 'Rob Walton', 'Alice Walton', 'David Thomson & family', 'Michael Dell', 'Gautam Adani', 'Phil Knight & family', 'Zhang Yiming', 'Dieter Schwarz', 'François Pinault & family', 'Klaus-Michael Kuehne', 'Giovanni Ferrero', 'Jacqueline Mars', 'John Mars', 'Li Ka-shing', 'Ma Huateng', 'Miriam Adelson & family', 'Ken Griffin', 'Mark Mateschitz', 'Robin Zeng', 'Tadashi Yanai & family', 'Len Blavatnik', 'Alain Wertheimer', 'Gerard Wertheimer', 'Gianluigi Aponte', 'Rafaela Aponte-Diamant', 'Colin Zheng Huang', 'Reinhold Wuerth & family', 'Lee Shau Kee', 'Jeff Yass', 'Jim Simons', 'Stephen Schwarzman', 'Susanne Klatten', 'Gina Rinehart', 'William Lei Ding', 'Germán Larrea Mota Velasco & family', 'Shiv Nadar', 'Low Tuck Kwong', 'Thomas Peterffy', 'Andrey Melnichenko & family', 'Stefan Quandt', 'MacKenzie Scott', 'R. Budi Hartono', 'Vladimir Potanin', 'Jack Ma', 'He Xiangjian & family', 'Iris Fontbona & family', 'Michael Hartono', 'James Ratcliffe', 'Cyrus Poonawalla', 'Masayoshi Son', 'Vladimir Lisin', 'Emmanuel Besnier', 'Abigail Johnson', 'Leonid Mikhelson & family', 'Lukas Walton', 'Wang Wei', 'Jensen Huang', 'Leonard Lauder', 'Takemitsu Takizaki', 'Alexey Mordashov & family', 'Vagit Alekperov', 'Thomas Frist, Jr. & family', 'Andrew Forrest', 'Ray Dalio', 'Li Eric', 'Wang Wenyin', 'Eyal Ofer', 'Qin Yinglin', 'Wang Chuanfu', 'Harold Hamm & family', 'David Tepper', 'Gennady Timchenko', 'Daniel Gilbert', 'Lakshmi Mittal', 'Steve Cohen', 'Carl Icahn', 'Savitri Jindal & family', 'Donald Bren', 'John Menard, Jr.', 'Rupert Murdoch & family', 'Vicky Safra & family', 'Theo Albrecht, Jr. & family', 'Renata Kellnerova & family', 'Li Xiting', 'Stefan Persson', 'Eric Schmidt', 'Michael Platt', 'Pang Kang', 'Karl Albrecht Jr. & family', 'Beate Heister', 'Jorge Paulo Lemann & family', 'Peter Woo', 'Dilip Shanghvi', 'Robert Pera', 'Radhakishan Damani', 'Huang Shilin', 'Dhanin Chearavanont', 'David Green & family', 'Charoen Sirivadhanabhakdi', 'Charlene de Carvalho-Heineken & family', 'Xu Hang', 'Wei Jianjun & family', 'Alisher Usmanov', 'Goh Cheng Liang', 'Kumar Birla', 'Aliko Dangote', 'Kwong Siu-hing', 'Idan Ofer', 'Chen Bang', 'Lui Che Woo', 'John Fredriksen', 'Diane Hendricks', 'Jan Koum', 'Jerry Jones', 'George Kaiser', 'Joseph Lau', 'Lu Xiangyang', 'Harry Triguboff', 'Uday Kotak', 'Stanley Kroenke', 'Mikhail Fridman', 'Sarath Ratanavadi', 'Dang Yanbao', 'Jiang Rensheng & family', 'Shahid Khan', 'Laurene Powell Jobs & family', 'Robert Kuok', 'Stephen Ross', 'Pavel Durov', 'Andreas Struengmann & family', 'Thomas Struengmann & family', 'Liu Hanyuan', 'Michael Rubin', 'Israel Englander', 'Viatcheslav Kantor', 'Anthony Pratt', 'Mikhail Prokhorov', 'Giorgio Armani', 'Johann Rupert & family', 'Gong Hongjia & family', 'Zhang Zhidong', 'Philip Anschutz', 'Judy Love & family', 'Ricardo Salinas Pliego & family', 'Donald Newhouse', 'Robert Kraft', 'Marcel Herrmann Telles', 'Suleiman Kerimov & family', 'Chris Xu', 'Changpeng Zhao', 'Andrew Beal', 'Mike Cannon-Brookes', 'Carl Cook', 'David Duffield', 'Jeffery Hildebrand', 'Viktor Rashnikov', 'Eduardo Saverin', 'Georg Schaeffler', 'Christy Walton', 'Scott Farquhar', 'Quek Leng Chan', 'Wu Yajun', 'Autry Stephens', 'Liu Yongxing', 'Vinod Adani', 'Nicolas Puech', 'Jacques Saadé, Jr.', 'Rodolphe Saadé', 'Tanya Saadé Zeenny', 'Melker Schorling & family', 'Andrei Guriev & family', 'Michael Kim', 'Lei Jun', 'Friedhelm Loh', 'Sun Piaoyang', 'Rick Cohen & family', 'Jin Baofang', 'Luo Liguo & family', 'Marijke Mars', 'Pamela Mars', 'Valerie Mars']
['$180 B', '$114 B', '$107 B', '$106 B', '$104 B', '$94.5 B', '$93 B', '$83.4 B', '$80.7 B', '$80.5 B', '$79.2 B', '$77.3 B', '$76 B', '$68 B', '$64.4 B', '$59 B', '$59 B', '$58.8 B', '$57.6 B', '$56.7 B', '$54.4 B', '$50.1 B', '$47.2 B', '$45.1 B', '$45 B', '$42.9 B', '$40.1 B', '$39.1 B', '$38.9 B', '$38.3 B', '$38.3 B', '$38 B', '$35.3 B', '$35 B', '$35 B', '$34.7 B', '$33.4 B', '$32.6 B', '$32.1 B', '$31.6 B', '$31.6 B', '$31.2 B', '$31.2 B', '$30.2 B', '$29.7 B', '$29.5 B', '$28.5 B', '$28.1 B', '$27.8 B', '$27.4 B', '$27 B', '$26.7 B', '$26.6 B', '$25.6 B', '$25.5 B', '$25.3 B', '$25.2 B', '$24.6 B', '$24.4 B', '$24.2 B', '$23.7 B', '$23.5 B', '$23.4 B', '$23.1 B', '$23.1 B', '$22.9 B', '$22.6 B', '$22.4 B', '$22.1 B', '$22 B', '$21.6 B', '$21.6 B', '$21.2 B', '$21.2 B', '$21.1 B', '$21 B', '$21 B', '$20.9 B', '$20.5 B', '$20.2 B', '$19.6 B', '$19.1 B', '$19 B', '$19 B', '$18.9 B', '$18.9 B', '$18.7 B', '$18.5 B', '$18.5 B', '$18.5 B', '$18 B', '$17.7 B', '$17.5 B', '$17.5 B', '$17.5 B', '$17.4 B', '$17.4 B', '$17.1 B', '$16.7 B', '$16.5 B', '$16.5 B', '$16.3 B', '$16.2 B', '$16.2 B', '$16 B', '$15.9 B', '$15.8 B', '$15.8 B', '$15.8 B', '$15.8 B', '$15.6 B', '$15.5 B', '$15.3 B', '$15.2 B', '$14.9 B', '$14.9 B', '$14.8 B', '$14.7 B', '$14.6 B', '$14.5 B', '$14.4 B', '$14.3 B', '$14.2 B', '$14.2 B', '$14.1 B', '$14 B', '$13.9 B', '$13.9 B', '$13.7 B', '$13.7 B', '$13.7 B', '$13.3 B', '$13.3 B', '$13.3 B', '$13.2 B', '$13.1 B', '$12.9 B', '$12.9 B', '$12.6 B', '$12.3 B', '$12.2 B', '$12.2 B', '$12.1 B', '$12 B', '$11.8 B', '$11.6 B', '$11.5 B', '$11.5 B', '$11.5 B', '$11.4 B', '$11.4 B', '$11.3 B', '$11.3 B', '$11.3 B', '$11.3 B', '$11.1 B', '$11.1 B', '$11 B', '$11 B', '$10.9 B', '$10.9 B', '$10.9 B', '$10.7 B', '$10.6 B', '$10.6 B', '$10.5 B', '$10.5 B', '$10.5 B', '$10.3 B', '$10.2 B', '$10.2 B', '$10.2 B', '$10.2 B', '$10.2 B', '$10.2 B', '$10.2 B', '$10.2 B', '$10.1 B', '$10.1 B', '$10.1 B', '$10 B', '$9.9 B', '$9.8 B', '$9.8 B', '$9.8 B', '$9.8 B', '$9.8 B', '$9.8 B', '$9.7 B', '$9.7 B', '$9.7 B', '$9.7 B', '$9.7 B', '$9.6 B', '$9.6 B', '$9.6 B', '$9.6 B', '$9.6 B', '$9.6 B']
['51', '59', '78', '92', '67', '81', '83', '65', '67', '69', '50', '87', '49', '68', '38', '87', '60', '74', '78', '73', '65', '58', '60', '85', '39', '83', '86', '85', '58', '83', '87', '94', '51', '77', '54', '30', '54', '74', '65', '74', '72', '82', '78', '43', '87', '95', '64', '84', '76', '60', '69', '51', '69', '77', '74', '78', '51', '56', '52', '82', '62', '58', '80', '80', '83', '70', '81', '65', '66', '52', '61', '67', '36', '52', '60', '90', '77', '57', '72', '84', '61', '73', '59', '55', '72', '57', '57', '77', '65', '70', '61', '72', '66', '87', '73', '90', '83', '92', '70', '72', '55', '72', '75', '67', '55', '67', 'N/A', 'N/A', '83', '76', '67', '45', '68', '56', '83', '81', '78', '68', '56', '59', '69', '95', '55', '65', '93', '67', '57', '94', '78', '76', '47', '80', '80', '71', '60', '90', '64', '75', '58', '57', '50', '69', '72', '59', '99', '82', '38', '73', '73', '59', '50', '74', '69', '62', '57', '88', '72', '58', '51', '83', '85', '67', '93', '81', '73', '57', '39', '45', '70', '43', '60', '82', '64', '74', '41', '58', '74', '43', '81', '59', '85', '74', '74', '80', '51', '53', '55', '75', '63', '59', '53', '76', '64', '70', '70', '67', '58', '62', '64']
['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'Mexico', 'India', 'United States', 'France', 'United States', 'Spain', 'United States', 'China', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'Canada', 'United States', 'India', 'United States', 'China', 'Germany', 'France', 'Germany', 'Italy', 'United States', 'United States', 'Hong Kong', 'China', 'United States', 'United States', 'Austria', 'Hong Kong', 'Japan', 'United States', 'France', 'France', 'Switzerland', 'Switzerland', 'China', 'Germany', 'Hong Kong', 'United States', 'United States', 'United States', 'Germany', 'Australia', 'China', 'Mexico', 'India', 'Indonesia', 'United States', 'Russia', 'Germany', 'United States', 'Indonesia', 'Russia', 'China', 'China', 'Chile', 'Indonesia', 'United Kingdom', 'India', 'Japan', 'Russia', 'France', 'United States', 'Russia', 'United States', 'China', 'United States', 'United States', 'Japan', 'Russia', 'Russia', 'United States', 'Australia', 'United States', 'China', 'China', 'Israel', 'China', 'China', 'United States', 'United States', 'Russia', 'United States', 'India', 'United States', 'United States', 'India', 'United States', 'United States', 'United States', 'Brazil', 'Germany', 'Czech Republic', 'Singapore', 'Sweden', 'United States', 'United Kingdom', 'China', 'Germany', 'Germany', 'Brazil', 'Hong Kong', 'India', 'United States', 'India', 'China', 'Thailand', 'United States', 'Thailand', 'Netherlands', 'Hong Kong', 'China', 'Russia', 'Singapore', 'India', 'Nigeria', 'Hong Kong', 'Israel', 'China', 'Hong Kong', 'Cyprus', 'United States', 'United States', 'United States', 'United States', 'Hong Kong', 'China', 'Australia', 'India', 'United States', 'Russia', 'Thailand', 'China', 'China', 'United States', 'United States', 'Malaysia', 'United States', 'United Arab Emirates', 'Germany', 'Germany', 'China', 'United States', 'United States', 'Russia', 'Australia', 'Russia', 'Italy', 'South Africa', 'Hong Kong', 'China', 'United States', 'United States', 'Mexico', 'United States', 'United States', 'Brazil', 'Russia', 'China', 'Canada', 'United States', 'Australia', 'United States', 'United States', 'United States', 'Russia', 'Brazil', 'Germany', 'United States', 'Australia', 'Malaysia', 'China', 'United States', 'China', 'Cyprus', 'France', 'France', 'France', 'France', 'Sweden', 'Russia', 'United States', 'China', 'Germany', 'China', 'United States', 'China', 'China', 'United States', 'United States', 'United States']
['Tesla, SpaceX', 'Amazon', 'Oracle', 'Berkshire Hathaway', 'Microsoft', 'Bloomberg LP', 'Telecom', 'Diversified', 'Microsoft', "L'Oréal", 'Google', 'Zara', 'Google', 'Beverages, pharmaceuticals', 'Facebook', 'Koch Industries', 'Koch Industries', 'Walmart', 'Walmart', 'Walmart', 'Media', 'Dell Technologies', 'Infrastructure, commodities', 'Nike', 'TikTok', 'Retail', 'Luxury goods', 'Shipping', 'Nutella, chocolates', 'Candy, pet food', 'Candy, pet food', 'Diversified', 'Internet media', 'Casinos', 'Hedge funds', 'Red Bull', 'Batteries', 'Fashion retail', 'Music, chemicals', 'Chanel', 'Chanel', 'Shipping', 'Shipping', 'E-commerce', 'Fasteners', 'Real estate', 'Trading, investments', 'Hedge funds', 'Investments', 'BMW, pharmaceuticals', 'Mining', 'Online games', 'Mining', 'Software services', 'Coal', 'Discount brokerage', 'Fertilizers, coal', 'BMW', 'Amazon', 'Banking, tobacco', 'Metals', 'E-commerce', 'Home appliances', 'Mining', 'Banking, tobacco', 'Chemicals', 'Vaccines', 'Internet, telecom', 'Steel, transport', 'Cheese', 'Fidelity', 'Gas, chemicals', 'Walmart', 'Package delivery', 'Semiconductors', 'Estee Lauder', 'Sensors', 'Steel, investments', 'Oil', 'Hospitals', 'Mining', 'Hedge funds', 'Automobiles', 'Mining, copper products', 'Real estate, shipping', 'Pig breeding', 'Batteries, automobiles', 'Oil & gas', 'Hedge funds', 'Oil, gas', 'Quicken Loans', 'Steel', 'Hedge funds', 'Investments', 'Steel', 'Real estate', 'Home improvement stores', 'Newspapers, TV network', 'Banking', "Aldi, Trader Joe's", 'Finance, telecommunications', 'medical devices', 'H&M', 'Google', 'Hedge funds', 'Soy sauce', 'Supermarkets', 'Supermarkets', 'Beer', 'Real estate', 'Pharmaceuticals', 'Wireless networking', 'Retail, investments', 'Batteries', 'Diversified', 'Retail', 'Alcohol, real estate', 'Heineken', 'Medical devices', 'Automobiles', 'Steel, telecom, investments', 'Paints', 'Commodities', 'Cement, sugar', 'Real estate', 'Shipping', 'Hospitals', 'Casinos/hotels', 'Shipping', 'Building supplies', 'WhatsApp', 'Dallas Cowboys', 'Oil & gas, banking', 'Real estate', 'Automobiles, batteries', 'Real estate', 'Banking', 'Sports, real estate', 'Oil, banking, telecom', 'Energy', 'Coal', 'Vaccines', 'Auto parts', 'Apple, Disney', 'Palm oil, shipping, property', 'Real estate', 'Messaging app', 'Pharmaceuticals', 'Pharmaceuticals', 'Agribusiness', 'Online retail', 'Hedge funds', 'Fertilizer, real estate', 'Manufacturing', 'Investments', 'Luxury goods', 'Luxury goods', 'Video surveillance', 'Internet media', 'Energy, sports, entertainment', 'Gas stations', 'Retail, media', 'Media', 'Manufacturing, New England Patriots', 'Beer', 'Gold', 'E-commerce', 'Cryptocurrency exchange', 'Banks, real estate', 'Software', 'Medical devices', 'Business software', 'Oil', 'Steel', 'Facebook', 'Auto parts', 'Walmart', 'Software', 'Banking, property', 'Real estate', 'Oil', 'Diversified', 'Infrastructure, commodities', 'Hermes', 'Shipping', 'Shipping', 'Shipping', 'Investments', 'Fertilizers', 'Private equity', 'Smartphones', 'Manufacturing', 'Pharmaceuticals', 'Warehouse automation', 'Solar panels', 'Chemicals', 'Candy, pet food', 'Candy, pet food', 'Candy, pet food']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

,Rank,Name,Net Worth,Age,Citizenship,Source,Industry
0,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",
1,3,Jeff Bezos,$114 B,59,United States,Amazon,
2,4,Larry Ellison,$107 B,78,United States,Oracle,
3,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,
4,6,Bill Gates,$104 B,67,United States,Microsoft,
...,...,...,...,...,...,...,...
194,195,Jin Baofang,$9.6 B,70,China,Solar panels,
195,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,
196,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",
197,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",
198,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",

# Q8. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [9]:
driver = webdriver.Chrome()
URL=input("Enter the URL: ")
driver.get(URL)


Comments = []
Upvote = []
Times = []

for _ in range(30):
    driver.execute_script("window.scrollBy(0,100)")
    time.sleep(5)
    comment = driver.find_elements(By.ID,"content-text")
    for i in comment:
        try:
            Comments.append(i.text)
        except:
            Comments.append("-")
        
    upvote = driver.find_elements(By.ID,"vote-count-middle")
    for i in upvote:
        try:
            Upvote.append(i.text)
        except:
            Upvote.append("-")
        
    times = driver.find_elements(By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]')
    for i in times:
        try:
            Times.append(i.text)
        except:
            Times.append("-")

print(len(Comments))  
print(len(Upvote))
print(len(Times))

df=pd.DataFrame({'Comments':Comments,'Comments Upvote':Upvote,'Time when comment is posted':Times})
df

Enter the URL: https://www.youtube.com/watch?v=EU8vG9_lPy8&t=1s
620
620
620

,Comments,Comments Upvote,Time when comment is posted
0,Hare Krishna. It has come to our attention tha...,480,1 year ago
1,I credit this piece for helping me finish so m...,147,1 year ago
2,"Dear Bhartiyas, We need to keep this gift give...",105,1 year ago
3,Your music is very calm and positive please re...,53,1 year ago
4,Please add more of such vedic music! Extremely...,77,2 years ago
...,...,...,...
615,Fantaaaaaaasstic Radhe-Krishna️,3,1 year ago
616,Wow... thank you so much... It's greatly effec...,1,1 year ago
617,Hare Krishna,10,2 years ago
618,Back to our roots!!,3,8 months ago
619,Music is superb but plz remove ads .This music...,4,1 year ago (edited)

# Q9. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [7]:
driver = webdriver.Chrome()

try:
    driver.get("https://www.hostelworld.com/")
    Location=driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[1]/div[1]/div/div[2]/div[4]/div/div[2]/div/div[1]/div/div/div/input")
    time.sleep(2)
    Location.send_keys("London")
    
    Search = driver.find_element(By.XPATH,"/html/body/div[3]/div/div/div[2]/div[1]/div/div/div[4]/div/div[2]/div/div[5]/button")
    Search.click()
    time.sleep(2)
except NoSuchElementException:
    driver.get("https://www.hostelworld.com/pwa/wds/s?q=London,%20England&country=London&city=London&type=city&id=3&from=2023-08-10&to=2023-08-13&guests=2&page=1")

time.sleep(3)

HostelName = []
Location = []
Ratings = []
TotalReview = []
OverallReview = []
Price=[]
Private = []
DormPrice = []
PropertyDescription = []
Url = []
Facilities=[]

Hostel = driver.find_elements(By.XPATH, '//div[@class="property-name"]')
try:
    for i in Hostel:
        HostelName.append(i.text)
except:
    HostelName.append("-")
HostelName.pop(0)

location = driver.find_elements(By.XPATH, '//span[@class="distance-description"]')
try:
    for i in location:
        Location.append(i.text)
except:
    Location.append("-")

rate = driver.find_elements(By.XPATH, '//span[@class="number"]')
try:
    for i in rate:
        Ratings.append(i.text.split("\n")[0])
except:
    Ratings.append("-")
Ratings.pop(0)

Review = driver.find_elements(By.XPATH, '//span[@class="left-margin"]')
try:
    for i in Review:
        TotalReview.append(i.text)
except:
    TotalReview.append("-")

review = driver.find_elements(By.XPATH, '//span[@class="keyword"]')
try:
    for i in review:
        OverallReview.append(i.text)
except:
    OverallReview.append("-")

price=driver.find_elements(By.XPATH, '//div[@class="property-accommodation-price"]')
try:
    for i in price:
        Price.append(i.text.replace("No Privates Available","-").replace("Privates From\n","").replace("Dorms From\n","").replace("No Dorms Available","-").replace("-20%\n₹24,624\n","").replace("-20%\n₹6,207\n","").replace("-10%\n₹3,293\n","").replace("-5%\n₹3,519\n","").replace("-10%\n₹2,999\n","").replace("-10%\n₹2,997\n","").replace("-10%\n₹2,450\n","").replace("-10%\n₹2,450\n","").replace("-10%\n₹2,684\n","").replace("-10%\n₹3,544\n","").replace("10%\n₹2,302\n","").replace("-5%\n₹3,201\n","").replace("-10%\n₹3,209\n","").replace("-10%\n₹2,488","").replace("-20%\n₹6,466\n","").replace("-10%\n₹2,457\n","").replace("-10%\n₹2,762\n",""))
except:
    Price.append("-")
Price.pop(0)

Private =Price[::2]
DormPrice = Price[1::2]

URL = driver.find_elements(By.XPATH, '//a[@rel="noreferrer noopener"]')
for i in URL:
    Url.append(i.get_attribute("href"))
    
time.sleep(4)
Url.pop(0)

for i in Url:
    driver.get(i)
    time.sleep(5)
    try:
        description = driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/section/div[9]/div/div[2]/div[5]/div/div[2]')
        PropertyDescription.append(description.text)
    except NoSuchElementException:
        PropertyDescription.append("-")
        
    try:
        Facility = driver.find_element(By.XPATH,'//ul[@class="facility-sections"]')
        Facilities.append(Facility.text)
    except NoSuchElementException:
        Facilities.append("-")

time.sleep(5)

df = pd.DataFrame({"Hostel Name": HostelName,"Distance from City Center": Location,"Ratings": Ratings,"Total Review": TotalReview,"Overall Review": OverallReview[0:30],"Private Price": Private[0:30],"Dorm Price": DormPrice,"Facilities":Facilities,"Description": PropertyDescription})
df

,Hostel Name,Distance from City Center,Ratings,Total Review,Overall Review,Private Price,Dorm Price,Facilities,Description
0,Wombat's City Hostel London,- 3.6km from city centre,9.0,(15139),Fabulous,"₹19,699","₹5,173",Free\nLinen Included Free City Maps Free WiFi ...,-
1,Onefam Notting Hill by Hostel One,- 5.5km from city centre,9.7,(2175),Superb,"₹17,764","₹5,196",Free\nLinen Included Free WiFi Free Internet A...,-
2,St Christopher's Village,- 1.8km from city centre,8.1,(12298),Superb,-,"₹2,964",Free\nLinen Included Free WiFi Free Internet A...,St Christopher's Inn at The Village in London ...
3,Generator London,- 3km from city centre,7.6,(7634),Fabulous,-,"₹3,642",Free\nLinen Included Free City Maps Free WiFi ...,Generator London is a design hotel-hostel loca...
4,Urbany Hostel London,- 5.4km from city centre,9.5,(850),Very Good,"₹19,163","₹4,554",Free\nLinen Included Free WiFi\nGeneral\nSecur...,-
5,Astor Hyde Park,- 4.3km from city centre,8.3,(12135),Superb,-,"₹2,815",Free\nLinen Included Free City Maps Free WiFi ...,Located in the most beautiful and charming nei...
6,Safestay London Elephant & Castle,- 1.7km from city centre,7.2,(5040),Fabulous,-,"₹2,265",Free\nLinen Included Free WiFi\nGeneral\nSecur...,Safestay at Elephant & Castle is ideal if you ...
7,Smart Hyde Park Inn Hostel,- 5km from city centre,7.4,(6679),Very Good,-,"₹2,888",Free\nLinen Included Free City Maps Free WiFi ...,-
8,Safestay London Kensington Holland Park,- 5.8km from city centre,7.0,(1606),Very Good,-,"₹2,162",Free\nLinen Included Free WiFi\nGeneral\nSecur...,-
9,Astor Museum Inn,- 2.2km from city centre,8.2,(9298),Very Good,-,"₹2,534",Free\nLinen Included Free City Maps Free WiFi\...,With the British Museum literally on its doors...
10,No.8 Willesden Hostel London,- 10km from city centre,6.5,(5056),Fabulous,-,"₹1,754",Free\nLinen Included Free WiFi\nGeneral\nSecur...,-
11,London Backpackers,- 11.9km from city centre,7.6,(4495),Good,-,"₹2,914",Free\nLinen Included Free City Maps Free WiFi ...,-
12,No.8 Seven Sisters,- 9km from city centre,5.2,(4040),Very Good,-,"₹1,754",Free\nLinen Included Free WiFi\nGeneral\nSecur...,-
13,Queen Elizabeth Chelsea,- 5.7km from city centre,7.3,(3535),Very Good,-,"₹3,242",Free\nLinen Included Free City Maps Free WiFi ...,-
14,Barmy Badger Backpackers,- 5.5km from city centre,9.0,(1955),Superb,"₹13,196","₹4,469",Free\nFree Breakfast Linen Included Free City ...,-
15,Saint James Backpackers,- 5.5km from city centre,7.7,(1909),Very Good,-,"₹4,328",Free\nFree Breakfast Linen Included Free City ...,We are located in central London - just 5 minu...
16,Astor Victoria,- 1.8km from city centre,7.1,(14999),Very Good,-,"₹2,569",Free\nLinen Included Free City Maps Free WiFi ...,With Victoria Station and Buckingham Palace a ...
17,St Christopher's Hammersmith,- 7.5km from city centre,7.4,(4273),Very Good,-,"\n₹2,239",Free\nLinen Included Free City Maps Free WiFi ...,Located within walking distance of Hammersmith...
18,St Christopher's Greenwich,- 7.6km from city centre,7.8,(3373),Very Good,-,"\n₹2,239",Free\nLinen Included Free City Maps Free WiFi ...,Discover South London's rich history in the ci...
19,St Christopher's Camden,- 4.3km from city centre,7.1,(4067),Very Good,-,"₹2,485",Free\nLinen Included Free City Maps Free WiFi ...,"Find our Camden hostel in London's north, smac..."
20,"PubLove @ The Steam Engine, Waterloo",- 0.5km from city centre,8.0,(410),Fabulous,-,"₹4,223",Free\nLinen Included Free City Maps Free WiFi\...,The heart & soul of London backpacking\nPull u...
21,Smart Camden Inn Hostel,- 4.4km from city centre,7.8,(3078),Very Good,-,"₹2,603",Free\nLinen Included Free City Maps Free WiFi\...,-
22,Bell House Hostel,- 4.2km from city centre,7.6,(80),Very Good,-,"₹3,262",Free\nLinen Included Free WiFi\nGeneral\nSecur...,-
23,Smart Hyde Park View Hostel,- 4.8km from city centre,7.8,(4709),Very Good,-,"₹3,385",Free\nLinen Included Free City Maps Free WiFi ...,Our Hyde Park View Hostel is in a superb locat...
24,St Christopher's Shepherds Bush,- 7km from city centre,7.1,(785),Very Good,-,"₹2,211",Free\nLinen Included Free City Maps Free WiFi\...,St Christopher's Inn Shepherds Bush gives trav...
25,Park Villa,- 6.3km from city centre,8.4,(909),Fabulous,"₹19,392","₹5,146",Free\nLinen Included Free WiFi Free Internet A...,-
26,Kabannas London St Pancras,- 3.3km from city centre,9.1,(2872),Superb,-,"₹3,800",Free\nLinen Included Free City Maps Free WiFi\...,Located opposite Kings Cross/St Pancras Intern...
27,The Backpackshack,- 10.9km from city centre,8.6,(768),Fabulous,"₹7,918",-,Free\nLinen Included Free Parking Towels Inclu...,-
28,YHA London St Pauls,- 1.9km from city centre,8.8,(2089),Fabulous,"₹18,298",-,Free\nLinen Included Free City Maps Free WiFi\...,YHA London St Paul's is temporarily unavailabl...
29,"PubLove @ The White Ferry, Victoria",- 2.4km from city centre,7.0,(358),Very Good,"₹42,227","₹3,519",Free\nLinen Included Free City Maps Free WiFi\...,"Walk to the river, turn left, and just keep wa..."