In [6]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\sruthi saji nair\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (0.10.3)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sniffio in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.2)
Requirement already satisfied: wsproto>=0.14 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [7]:
!pip install webdriver_manager

Requirement already satisfied: webdriver_manager in c:\users\sruthi saji nair\anaconda3\lib\site-packages (4.0.0)
Requirement already satisfied: requests in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from webdriver_manager) (2.31.0)
Requirement already satisfied: python-dotenv in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from webdriver_manager) (1.0.0)
Requirement already satisfied: packaging in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from webdriver_manager) (23.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from requests->webdriver_manager) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from requests->webdriver_manager) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from requests->webdriver_manager) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from requests->webdriver_manager) (2023.7.22)

In [8]:
import selenium
import pandas as pd
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import urllib.request
import undetected_chromedriver as uc
try:
    service = Service(ChromeDriverManager().install())
except ValueError:
    latest_chromedriver_version_url = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"
    latest_chromedriver_version = urllib.request.urlopen(latest_chromedriver_version_url).read().decode('utf-8')
    service = Service(ChromeDriverManager(version=latest_chromedriver_version).install())
driver_executable_path = service.path

options = uc.ChromeOptions()
import time
import requests
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException
import re

In [9]:
latestchromedriver = ChromeDriverManager().install()

# Q1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: 
A) Rank 
B) Name 
C) Artist 
D) Upload date 
E) Views

In [45]:
driver = uc.Chrome()
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
time.sleep(2)

Rank=[]
Name=[]
Artist=[]
UploadDate=[]
Views=[]

rank = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
try:
    for i in rank[0:30]:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("-")


name = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')
try:
    for i in name[0:30]:
        Name.append(i.text)
except NoSuchElementException:
    Name.append("-")

artist = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
try:
    for i in artist[0:30]:
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("-")

upload = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
try:
    for i in upload[0:30]:
        UploadDate.append(i.text)
except NoSuchElementException:
    UploadDate.append("-")
    
views = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
try:
    for i in views[0:30]:
        Views.append(i.text)
except NoSuchElementException:
    Views.append("-")

print("Rank=",len(Rank))
print("Name=",len(Name))
print("Artist=",len(Artist))
print("UploadDate=",len(UploadDate))
print("Views=",len(Views))

df = pd.DataFrame({'Rank': Rank, 'Name': Name,'Artist': Artist, 'Upload Date': UploadDate,'Views': Views})
df

Rank= 30
Name= 30
Artist= 30
UploadDate= 30
Views= 30

,Rank,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - children's songs,"June 17, 2016",13.18
1,2.,"""Despacito""[9]",Luis Fonsi,"January 12, 2017",8.23
2,3.,"""Johny Johny Yes Papa""[16]",LooLoo Kids - nursery rhymes,"October 8, 2016",6.76
3,4.,"""Bath Song""[17]",Cocomelon - nursery rhymes,"May 2, 2018",6.33
4,5.,"""Shape of You""[18]",Ed Sheeran,"January 30, 2017",6.05
5,6.,"""See You Again""[21]",Wiz Khalifa,"April 6, 2015",5.98
6,7.,"""Wheels on the Bus""[26]",Cocomelon - nursery rhymes,"May 24, 2018",5.46
7,8.,"""Phonics Song with Two Words""[27]",ChuChu TV - children's songs,"March 6, 2014",5.42
8,9.,"""Uptown Funk""[28]",Mark Ronson,"November 19, 2014",5.00
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[29]",Miroshka TV - children's songs,"February 27, 2018",4.94
10,11.,"""Gangnam Style""[30]",Psy,"July 15, 2012",4.86
11,12.,"""Masha and the Bear – Recipe for Disaster""[35]",Get Movies - children's songs,"January 31, 2012",4.55
12,13.,"""Dame Tu Cosita""[36]",El Chombo,"April 5, 2018",4.41
13,14.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",4.00
14,15.,"""Sugar""[38]",Maroon 5,"January 14, 2015",3.91
15,16.,"""Roar""[39]",Katy Perry,"September 5, 2013",3.84
16,17.,"""Counting Stars""[40]",OneRepublic,"May 31, 2013",3.84
17,18.,"""Baa Baa Black Sheep""[41]",Cocomelon - nursery rhymes,"June 25, 2018",3.73
18,19.,"""Sorry""[42]",Justin Bieber,"October 22, 2015",3.69
19,20.,"""Waka Waka (This Time for Africa)""[43]",Shakira,"June 4, 2010",3.68
20,21.,"""Thinking Out Loud""[44]",Ed Sheeran,"October 7, 2014",3.63
21,22.,"""Lakdi Ki Kathi""[45]",Jingle Toons,"June 14, 2018",3.63
22,23.,"""Dark Horse""[46]",Katy Perry,"February 20, 2014",3.56
23,24.,"""Perfect""[47]",Ed Sheeran,"November 9, 2017",3.51
24,25.,"""Faded""[48]",Alan Walker,"December 3, 2015",3.49
25,26.,"""Let Her Go""[49]",Passenger,"July 25, 2012",3.48
26,27.,"""Humpty the train on a fruits ride""[50]",Kiddiestv Hindi - children's songs,"January 26, 2018",3.51
27,28.,"""Girls Like You""[51]",Maroon 5,"May 31, 2018",3.45
28,29.,"""Bailando""[52]",Enrique Iglesias,"April 11, 2014",3.43
29,30.,"""Lean On""[53]",Major Lazer,"March 22, 2015",3.43

# Q2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. You need to find following details: 
A) Match title (I.e. 1 ODI) 
B) Series 
C) Place 
D) Date 
E) Time 
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [5]:
driver = webdriver.Chrome()
driver.get("https://www.bcci.tv/")
time.sleep(2)
        
driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a').click()


MatchTitle=[]
Series=[]
Place=[]
Date=[]
Times=[]
time.sleep(3)

for _ in range(1):
    driver.execute_script("window.scrollBy(0,1000)")
    time.sleep(3)
    try:
        driver.find_element(By.XPATH,'//button[@class="match-btn btn-red d-flex align-items-center justify-content-center mx-auto mt-3"]').click()
    except ElementClickInterceptedException :
        pass
    
match = driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
try:
    for i in match:
        MatchTitle.append(i.text)
except NoSuchElementException:
    MatchTitle.append("-")
    
series = driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
try: 
    for i in series:
        Series.append(i.text)
except NoSuchElementException:
    Series.append("-")
    
place = driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
try: 
    for i in place:
        Place.append(i.text)
except NoSuchElementException:
    Place.append("-")
        
date = driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
try: 
    for i in date:
        Date.append(i.text)
except NoSuchElementException:
    Date.append("-")
        
times = driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
try: 
    for i in times:
         Times.append(i.text)
except NoSuchElementException:
    Times.append("-")
    
print("Match Title = ",len(MatchTitle))
print("Series = ",len(Series))
print("Place = ",len(Place))
print("Date = ",len(Date))
print("Times = ",len(Times))

df=pd.DataFrame({"Match Title": MatchTitle,"Series": Series,"Place": Place,"Date" : Date,"Time":Times})
df

Match Title =  16
Series =  16
Place =  16
Date =  16
Times =  16

,Match Title,Series,Place,Date,Time
0,INDIA TOUR OF IRELAND 2023,1st T20I -,Dublin,18 AUG 2023,7:30 PM IST
1,INDIA TOUR OF IRELAND 2023,2nd T20I -,Dublin,20 AUG 2023,7:30 PM IST
2,INDIA TOUR OF IRELAND 2023,3rd T20I -,Dublin,23 AUG 2023,7:30 PM IST
3,ASIA CUP 2023,1st ODI -,Pallekele,2 SEP 2023,10:00 AM IST
4,ASIA CUP 2023,2nd ODI -,Pallekele,4 SEP 2023,10:00 AM IST
5,AUSTRALIA TOUR OF INDIA 2023-24,1st ODI -,Mohali,22 SEP 2023,1:30 PM IST
6,AUSTRALIA TOUR OF INDIA 2023-24,2nd ODI -,Indore,24 SEP 2023,1:30 PM IST
7,AUSTRALIA TOUR OF INDIA 2023-24,3rd ODI -,Rajkot,27 SEP 2023,1:30 PM IST
8,ICC MENS WORLD CUP 2023,1st ODI -,Chennai,8 OCT 2023,2:00 PM IST
9,ICC MENS WORLD CUP 2023,2nd ODI -,Delhi,11 OCT 2023,2:00 PM IST
10,ICC MENS WORLD CUP 2023,3rd ODI -,Ahmedabad,14 OCT 2023,2:00 PM IST
11,ICC MENS WORLD CUP 2023,4th ODI -,Pune,19 OCT 2023,2:00 PM IST
12,ICC MENS WORLD CUP 2023,5th ODI -,Dharamsala,22 OCT 2023,2:00 PM IST
13,ICC MENS WORLD CUP 2023,6th ODI -,Lucknow,29 OCT 2023,2:00 PM IST
14,ICC MENS WORLD CUP 2023,7th ODI -,Mumbai,2 NOV 2023,2:00 PM IST
15,ICC MENS WORLD CUP 2023,8th ODI -,Kolkata,5 NOV 2023,2:00 PM IST

# Q3. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/You have to find following details: 
A) Rank 
B) State 
C) GSDP(18-19)- at current prices 
D) GSDP(19-20)- at current prices 
E) Share(18-19) 
F) GDP($ billion) 
Note: - From statisticstimes home page you have to reach to economy page through code.

In [14]:
driver = webdriver.Chrome()
driver.get("http://statisticstimes.com/")
time.sleep(2)

driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button').click()
time.sleep(1)
driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]').click()
try:
    driver.find_element(By.XPATH,'//div[@class="btn skip"]').click()
    driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
except NoSuchElementException:
    driver.get("https://www.statisticstimes.com/economy/india/indian-states-gdp.php")

time.sleep(3)

Rank=[]
State=[]
GSDP_18_19 =[]
GSDP_19_20 =[]
Share_18_19=[]
GDP=[]

rank = driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[1]')
try:
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("-")

state = driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[2]')
try:
    for i in state:
        State.append(i.text)
except NoSuchElementException:
    State.append("-")

gsdp_18_19 = driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[4]')
try:
    for i in gsdp_18_19:
        GSDP_18_19.append(i.text)
except NoSuchElementException:
    GSDP_18_19.append("-")

gsdp_19_20 = driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[3]')
try:
    for i in gsdp_19_20:
        GSDP_19_20.append(i.text)
except NoSuchElementException:
    GSDP_19_20.append("-")

share_18_19 = driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[5]')
try:
    for i in share_18_19:
        Share_18_19.append(i.text)
except NoSuchElementException:
    Share_18_19.append("-")
    
gdp = driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[6]')
try:
    for i in gdp:
        GDP.append(i.text)
except NoSuchElementException:
    GDP.append("-")
    
df = pd.DataFrame({'Rank': Rank, 'State': State,'GSDP(18_19)': GSDP_18_19, 'GSDP(19_20)': GSDP_19_20,'Share(18_19)': Share_18_19,'GDP ': GDP})
df

,Rank,State,GSDP(18_19),GSDP(19_20),Share(18_19),GDP
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"25,141","28,391",0.15%,"17,060"
62,30,Nagaland,"24,534",-,0.15%,-
63,31,Arunachal Pradesh,"22,488",-,0.13%,-
64,32,Mizoram,"20,947","24,424",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

# Q4. Scrape the details of trending repositories on Github.com.Url = https://github.com/ You have to find the following details: 
A) Repository title 
B) Repository description 
C) Contributors count 
D) Language used

In [10]:
driver =uc.Chrome(driver_executable_path=driver_executable_path, options=options)
driver_executable_path = service.path
driver.get("https://github.com/")
time.sleep(2)
driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button').click()
time.sleep(2)
driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a').click()
time.sleep(2)

RepositoryTitle=[]
RepositoryDescription=[]
Contributors=[]
LanguageUsed=[]

URL=[]

repositorytitle = driver.find_elements(By.XPATH,'//a[@class="Link"]')
try:
    for i in repositorytitle:
        RepositoryTitle.append(i.text)
        URL.append(i.get_attribute('href'))
except NoSuchElementException:
    RepositoryTitle.append("-")
    
try:
    repositorydescription = driver.find_elements(By.XPATH,'//article[@class="Box-row"]/p')
    for i in repositorydescription:
        RepositoryDescription.append(i.text)
except:
    RepositoryDescription.append("-")
print(RepositoryDescription)

for j in URL:
    driver.get(j)
    driver.implicitly_wait(2)
    c=driver.find_elements(By.XPATH,'//div[@class="BorderGrid BorderGrid--spacious"]/div')
    try:
        Contributors.append(((c[2].text).split())[1])
    except NoSuchElementException:
        Contributors.append("-")
        
   
    try:
            Language=[]
            LanguageUsed.append(((c[1].text).split())[1::2])
    except NoSuchElementException:
        LanguageUsed.append("-")

        
    


print("URL =",len(URL))
print("Repository Title = ",len(RepositoryTitle))
print("Repository Description = ",len(RepositoryDescription))
print("Contributors = ",len(Contributors))
print("Language Used = ",len(LanguageUsed))

df=pd.DataFrame({"Repository Title" : RepositoryTitle, "Repository Description":RepositoryDescription,"Contributors":Contributors,"Language Used": LanguageUsed})
df

[]
URL = 0
Repository Title =  0
Repository Description =  0
Contributors =  0
Language Used =  0

Empty DataFrame
Columns: [Repository Title, Repository Description, Contributors, Language Used]
Index: []

# Q5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the following details: 
A) Song name 
B) Artist name 
C) Last week rank 
D) Peak rank 
E) Weeks on board 
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [5]:

driver =uc.Chrome(driver_executable_path=driver_executable_path, options=options)
driver_executable_path = service.path
driver.get("https://www.billboard.com/")
time.sleep(5)
driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a').click()
time.sleep(3)
try:
    driver.find_element(By.XPATH,'//button[@class="_2KpZ6l _2doB4z"]').click()
except:
    print("No pop-up-1")
try:
    driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a').click()
except:
    driver.get("https://www.billboard.com/charts/hot-100/")
time.sleep(3)

SongName=[]
ArtistName=[]
LastWeekRank=[]
PeakRank=[]
WeeksOnBoard=[]

Songname=driver.find_element(By.XPATH,'//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet"]')
SongName.append(Songname.text)
songname=driver.find_elements(By.XPATH,'//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]')
for i in songname:
    SongName.append(i.text)

Artistname=driver.find_element(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet"]')
ArtistName.append(Artistname.text)
artistname=driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
for i in artistname:
    ArtistName.append(i.text)
rank=[]
rankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
for i in rankTag[:3]:
    rank.append(i.text )
Rank=[]  
RankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
for i in RankTag:
    Rank.append(i.text)

for i in Rank:
    if i=='':
        Rank.remove(i)

LastWeekRank=Rank[0::3]
LastWeekRank.insert(0,rank[0])
PeakRank=Rank[1::3]
PeakRank.insert(0,rank[1])
WeeksOnBoard=Rank[2::3]
WeeksOnBoard.insert(0,rank[2])

df=pd.DataFrame({"Name":SongName[:100],"Artist":ArtistName[:100],"Last Week Rank":LastWeekRank[0:100],"Peak Rank":PeakRank[0:100],"Weeks On Board":WeeksOnBoard[0:100]})
df

No pop-up-1

,Name,Artist,Last Week Rank,Peak Rank,Weeks On Board
0,Last Night,Morgan Wallen,1,1,28
1,Fast Car,Luke Combs,2,2,20
2,Cruel Summer,Taylor Swift,4,3,14
3,Calm Down,Rema & Selena Gomez,6,3,49
4,Fukumean,Gunna,7,4,8
...,...,...,...,...,...
95,Lagunas,Peso Pluma & Jasiel Nunez,-,82,1
96,Overdrive,Post Malone,,,
97,"Bzrp Music Sessions, Vol. 55",Bizarrap & Peso Pluma,55,55,2
98,Dawns,Zach Bryan Featuring Maggie Rogers,,,
99,Rubicon,Peso Pluma,96,19,7

# Q6. Scrape the details of Highest selling novels.
A) Book name 
B) Author name 
C) Volumes sold 
D) Publisher 
E) Genre

In [11]:
driver =uc.Chrome(driver_executable_path=driver_executable_path, options=options)
driver_executable_path = service.path
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
time.sleep(5)

BookName=[]
AuthorName=[]
VolumesSold=[]
Publisher=[]
Genre=[]

bookname=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[2]')
try:
    for i in bookname:
        BookName.append(i.text)
except:
    BookName.append("-")
    
authorname=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[3]')
try:
    for i in authorname:
        AuthorName.append(i.text)
except:
    author_name.append("-")
    
volumessold=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[4]')
try:
    for i in volumessold:
        VolumesSold.append(i.text)
except:
    VolumesSold.append("-")
    
publisher=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[5]')
try:
    for i in publisher:
        Publisher.append(i.text)
except:
    Publisher.append("-")
    
genre=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[6]')
try:
    for i in genre:
        Genre.append(i.text)
except:
    Genre.append("-")
    

df=pd.DataFrame({'Book Name':BookName,'Author Name':AuthorName,'Volumes sold':VolumesSold,'Publisher':Publisher,'Genre':Genre})
df

,Book Name,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q7. Scrape the details most watched tv series of all time from imdb.com. 
Url = https://www.imdb.com/list/ls095964455/ You 
have to find the following details: 
A) Name 
B) Year span 
C) Genre 
D) Run time 
E) Ratings 
F) Votes

In [5]:
driver =uc.Chrome(driver_executable_path=driver_executable_path, options=options)
driver_executable_path = service.path
driver.get("https://www.imdb.com/list/ls095964455/")
time.sleep(5)

Name=[]
Year=[]
Genre=[]
RunTime=[]
Ratings=[]
Votes=[]

name=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
try:
    for i in name:
        Name.append(i.text)
except:
    Name.append("-") 
    
year=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]')
try:
    for i in year:
        Year.append(i.text)
except:
    Year.append("-")   

genre=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[5]')
try:
    for i in genre:
        Genre.append(i.text)
except:
    Genre.append("-")

time=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')
try:
    for i in time:
        RunTime.append(i.text)
except:
    RunTime.append("-")   

rating=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div/span[2]')
try:
    for i in rating:
        Ratings.append(i.text)
except:
    Ratings.append("-")
    
vote=driver.find_elements(By.XPATH,'//span[@name="nv"]')
try:
    for i in vote:
        Votes.append(i.text)
except:
    Votes.append("-")
    
df=pd.DataFrame({'Name':Name,'Year Span':Year,'Genre':Genre,'Run Time':RunTime,'Ratings':Ratings,'Votes':Votes})
df

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,194,104"
1,Stranger Things,(2016–2024),"Drama, Fantasy, Horror",51 min,8.7,"1,267,722"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,041,432"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"306,099"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"265,173"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"52,469"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"64,490"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"210,185"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"43,705"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"263,859"

# Q8. Details of Datasets from UCI machine learning repositories. 
Url = https://archive.ics.uci.edu/
You have to find the following details: 
A) Dataset name 
B) Data type 
C) Task 
D) Attribute type 
E) No of instances 
F) No of attribute G) Year 
Note: - from the home page you have to go to the Show All Dataset page through code

In [5]:
driver =uc.Chrome(driver_executable_path=driver_executable_path, options=options)
driver_executable_path = service.path
driver.get(" https://archive.ics.uci.edu/")
time.sleep(5)

DataSet= driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]").click()

Data=[]
DatasetName=[]
Task=[]
Instances=[]
DataType=[]
Attributes=[]

data=driver.find_elements(By.XPATH,'//div[@class="rounded-box bg-base-100"]/div/div[2]/h2')
try:
    for i in data:
        DatasetName.append(i.text)
except:
    DatasetName.append("-") 

task=driver.find_elements(By.XPATH,'//div[@class="rounded-box bg-base-100"]/div/div[2]/div/div[1]')
try:
    for i in task:
        Task.append(i.text)
except:
    Task.append("-")

mv=driver.find_elements(By.XPATH,'//div[@class="rounded-box bg-base-100"]/div/div[2]/div/div[2]/span')
try:
    for i in mv:
        Instances.append(i.text)
except:
    Instances.append("-")
    
attributes=driver.find_elements(By.XPATH,'//div[@class="rounded-box bg-base-100"]/div/div[2]/div/div[3]/span')
try:
    for i in attributes:
        Attributes.append(i.text)
except:
    Attributes.append("-")


df= pd.DataFrame({"Dataset name":DatasetName,"Instances":Instances,"Task":Task,"Attributes":Attributes})
df

,Dataset name,Instances,Task,Attributes
0,Iris,150 Instances,Classification,4 Attributes
1,Heart Disease,303 Instances,Classification,13 Attributes
2,Adult,48.84K Instances,Classification,14 Attributes
3,Dry Bean Dataset,13.61K Instances,Classification,16 Attributes
4,Diabetes,,,20 Attributes
5,Wine,178 Instances,Classification,13 Attributes
6,Room Occupancy Estimation,10.13K Instances,Classification,16 Attributes
7,Image Recognition Task Execution Times in Mobi...,4K Instances,Regression,2 Attributes
8,Rocket League Skillshots,297 Instances,Classification,
9,TUANDROMD (Tezpur University Android Malware D...,4.46K Instances,Classification,241 Attributes
10,REJAFADA,2K Instances,Classification,6.83K Attributes
11,Higher Education Students Performance Evaluation,145 Instances,Classification,33 Attributes