In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\sruthi saji nair\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (0.10.3)
Requirement already satisfied: trio~=0.17 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (0.22.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (2022.12.7)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: attrs>=20.1.0 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: cffi>=1.14 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.2)
Requirement already satisfied: sniffio in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: sortedcontainers in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [3]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

# Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.

In [4]:
driver = webdriver.Chrome()
driver.get("http://www.naukri.com/")

Designation = driver.find_element(By.CLASS_NAME,"suggestor-input")
Designation.send_keys('Data Analyst')

Location = driver.find_element(By.XPATH,'//input[@placeholder="Enter location"]')
Location.send_keys('Bangalore')

Search = driver.find_element(By.CLASS_NAME,"qsbSubmit")
Search.click()

time.sleep(3)

job_title=[]
job_location=[]
company_name=[]
experience_required=[]

title_tags = driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)

    
location_tags = driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft locWdth"]')
for i in location_tags[0:10]:
    location=i.text
    job_location.append(location)

company_tags = driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company_tags[0:10]:
    company=i.text
    company_name.append(company)
    
experience_tags = driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft expwdth"]')
for i in experience_tags[0:10]:
    experience=i.text
    experience_required.append(experience)
    
    
df = pd.DataFrame({'Job Title': job_title, 'Job Location': job_location,'Company Name': company_name, 'Experience required': experience_required})
df

,Job Title,Job Location,Company Name,Experience required
0,Data Analyst,Bangalore/Bengaluru,Eastvantage,4-6 Yrs
1,Data Analyst,"Bangalore/ Bengaluru, Karnataka, Gurgaon/ Guru...",Delhivery,1-3 Yrs
2,Data Analyst,Bangalore/Bengaluru,Everest Vacuum,2-5 Yrs
3,Data Analyst,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",Boomi Software,1-5 Yrs
4,Data Analyst,"Bangalore/Bengaluru, Hyderabad/Secunderabad, Pune",Synechron,5-8 Yrs
5,Data Analyst,"Bangalore/Bengaluru, Hyderabad/Secunderabad, Pune",Synchron Infotech,5-8 Yrs
6,Data Analyst I,Bangalore/Bengaluru,Cerner,5-10 Yrs
7,Data Analyst,Bangalore/Bengaluru,Persolkelly India,0-2 Yrs
8,Data Analyst,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",Truthfools,3-8 Yrs
9,Data Analyst | HyVee,Bangalore/Bengaluru,Talent500,3-5 Yrs

# Q2:Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data.

In [43]:
driver = webdriver.Chrome()
driver.get("http://www.naukri.com/")

Designation = driver.find_element(By.CLASS_NAME,"suggestor-input")
Designation.send_keys('Data Scientist')

Location = driver.find_element(By.XPATH,'//input[@placeholder="Enter location"]')
Location.send_keys('Bangalore')

Search = driver.find_element(By.CLASS_NAME,"qsbSubmit")
Search.click()

time.sleep(3)

job_title=[]
job_location=[]
company_name=[]
experience_required=[]

title_tags = driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)

location_tags = driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft locWdth"]')
for i in location_tags[0:10]:
    location=i.text
    job_location.append(location)

company_tags = driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company_tags[0:10]:
    company=i.text
    company_name.append(company)
    
experience_tags = driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft expwdth"]')
for i in experience_tags[0:10]:
    experience=i.text
    experience_required.append(experience)
    
    
df = pd.DataFrame({'Job Title': job_title, 'Job Location': job_location,'Company Name': company_name, 'Experience required': experience_required})
df

,Job Title,Job Location,Company Name,Experience required
0,Analystics & Modeling Specialist,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",Accenture,6-8 Yrs
1,Data Science Specialist,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",Accenture,2-4 Yrs
2,Data Scientist,"Bangalore/Bengaluru, Mumbai (All Areas)",PwC,3-6 Yrs
3,Data Scientist,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",Tredence,2-4 Yrs
4,Data Scientist,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",IBS Software Services,5-8 Yrs
5,ACN - Applied Intelligence - Finance - Data Sc...,"Bangalore/Bengaluru, Hyderabad/Secunderabad, P...",Accenture,2-7 Yrs
6,Senior Data Scientist,"Bangalore/Bengaluru, Mumbai",Fractal Analytics,5-10 Yrs
7,Data Scientist,"Hybrid - Bangalore/ Bengaluru, Karnataka, Noid...",HCLTech,7-12 Yrs
8,Data Scientist with Retail Domain,"Bangalore/Bengaluru, Kolkata, Mumbai, Nagpur, ...",TRH Consultancy Services,4-9 Yrs
9,Data Scientist,"Bangalore/Bengaluru, Noida, Kolkata, Mumbai, H...",TRH Consultancy Services,5-10 Yrs

# Q3: In this question you have to scrape data using the filters available on the webpage as shown below:
You have to use the location and salary filter.
You have to scrape data for “Data Scientist” designation for first 10 job results.
You have to scrape the job-title, job-location, company name, experience required. 
The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs

In [6]:
driver = webdriver.Chrome()
driver.get("http://www.naukri.com/")

Designation = driver.find_element(By.CLASS_NAME,"suggestor-input")
Designation.send_keys('Data Scientist')

Search = driver.find_element(By.CLASS_NAME,"qsbSubmit")
Search.click()

time.sleep(3)

driver.find_element(By.XPATH,"//span[@title='Delhi / NCR']").click()
time.sleep(3)

driver.find_element(By.XPATH,"//span[@title='3-6 Lakhs']").click()
time.sleep(3)

job_title=[]
job_location=[]
company_name=[]
experience_required=[]

title_tags = driver.find_elements(By.XPATH,'//a[@class="title ellipsis"]')
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)

location_tags = driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft locWdth"]')
for i in location_tags[0:10]:
    location=i.text
    job_location.append(location)

company_tags = driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company_tags[0:10]:
    company=i.text
    company_name.append(company)
    
experience_tags = driver.find_elements(By.XPATH,'//span[@class="ellipsis fleft expwdth"]')
for i in experience_tags[0:10]:
    experience=i.text
    experience_required.append(experience)
    
    
df = pd.DataFrame({'Job Title': job_title, 'Job Location': job_location,'Company Name': company_name, 'Experience required': experience_required})
df

,Job Title,Job Location,Company Name,Experience required
0,Junior Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Analytos,0-2 Yrs
1,Data Scientist,"Gurgaon/Gurugram, Bangalore/Bengaluru",Blackbuck,3-7 Yrs
2,Data Scientist/ Senior Data Scientist/ Manager...,"Noida, Kolkata, Mumbai, Chandigarh, Hyderabad/...",Dreambig It Solutions India,1-6 Yrs
3,Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Analytos,2-4 Yrs
4,Data Scientist,Noida,Times Internet,3-8 Yrs
5,Python and ML Trainer,"Hyderabad/Secunderabad, New Delhi, Pune, Gurga...",Thescholar,3-8 Yrs
6,Hiring For Data Scientist,Remote,Infogain,4-9 Yrs
7,Junior Data Scientist,"Gurgaon/Gurugram, United States (USA), Bulgaria",Adidas,1-6 Yrs
8,Associate Data Scientist - ML & NLP,Gurgaon/Gurugram,Gartner,2-4 Yrs
9,Data Scientist,Noida,Gujarat Fluorochemicals,1-2 Yrs

# Q4: Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes:
1. Brand
2. ProductDescription
3. Price

In [52]:
driver = webdriver.Chrome()
driver.get("https://www.flipkart.com/")

time.sleep(5)

try:
    driver.find_element(By.XPATH,'//button[@class="_2KpZ6l _2doB4z"]').click()
except:
    print("No pop-up-1")

time.sleep(3)

Designation = driver.find_element(By.CLASS_NAME,"_3704LK")
Designation.send_keys('sunglasses')

time.sleep(1)

Search = driver.find_element(By.XPATH,'//button[@class="L0Z3Pu"]')
Search.click()

time.sleep(3)

brand=[]
product_description=[]
price=[]
for page in range(0,3):
    brand_tags = driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    for i in brand_tags[0:100]:
        b=i.text
        brand.append(b)
    product_tags = driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    for i in product_tags[0:100]:
        p=i.text
        product_description.append(p)
        
    price_tags = driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    for i in price_tags[0:100]:
        pr=i.text
        price.append(pr)
        
time.sleep(3)
nextpage = driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
nextpage.click()


df = pd.DataFrame({'Brand': brand[0:100], 'Product Description': product_description[0:100],'Price': price[0:100]})
df

            Brand                                Product Description Price
0   VINCENT CHASE  Polarized, UV Protection Rectangular Sunglasse...  ₹499
1   VINCENT CHASE     Polarized, UV Protection Round Sunglasses (51)  ₹949
2           SDEEP  UV Protection, Others Spectacle Sunglasses (Fr...  ₹185
3            SRPM             UV Protection Wayfarer Sunglasses (50)  ₹194
4       Elligator  UV Protection Cat-eye, Retro Square, Oval, Rou...  ₹168
..            ...                                                ...   ...
95           SRPM  by Lenskart Polarized, UV Protection Cat-eye S...  ₹194
96  VINCENT CHASE  UV Protection Retro Square Sunglasses (Free Size)  ₹648
97  VINCENT CHASE                UV Protection Round Sunglasses (50)  ₹499
98           MEHJ             UV Protection Wayfarer Sunglasses (59)  ₹299
99        ROADWAY  UV Protection, Others Wayfarer, Retro Square, ...  ₹256

[100 rows x 3 columns]

# Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link: 
https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market
1. Rating
2. Review summary
3. Full review
4. You have to scrape this data for first 100reviews.

In [55]:
driver = webdriver.Chrome()
driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market")

time.sleep(5)

try:
    driver.find_element(By.XPATH,'//button[@class="_2KpZ6l _2doB4z"]').click()
except:
    print("No pop-up")

time.sleep(3)

rating=[]
review_summary=[]
full_review=[]

for page in range(0,10):
    rating_tags = driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
    for i in rating_tags[0:100]:
        rate=i.text
        rating.append(rate)
    review_tags = driver.find_elements(By.XPATH,'//p[@class="_2-N8zT"]')
    for i in review_tags[0:100]:
        review=i.text
        review_summary.append(review)
        
    fullreview_tags = driver.find_elements(By.XPATH,'//div[@class="t-ZTKy"]')
    for i in fullreview_tags[0:100]:
        freview=i.text
        full_review.append(freview)
        
time.sleep(3)
nextpage = driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
nextpage.click()


df = pd.DataFrame({'Rating': rating[0:100], 'Review Summary': review_summary[0:100],'Full Review': full_review[0:100]})
df

No pop-up

,Rating,Review Summary,Full Review
0,5,Classy product,Camera is awesome\nBest battery backup\nA perf...
1,5,Mind-blowing purchase,Photos super
2,5,Wonderful,This is amazing at all
3,5,Terrific,Very very good
4,5,Fabulous!,Super🔥 and good performance 👌❤️
...,...,...,...
95,5,Just wow!,Perfect Product!!
96,5,Must buy!,It’s really awesome
97,5,Perfect product!,V Good all
98,5,Best in the market!,Good Camera
99,5,Worth every penny,Feeling awesome after getting the delivery of ...

# Q6: Scrape data forfirst 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.You have to scrape 3 attributes of each sneaker:
1. Brand
2. ProductDescription
3. Price

In [56]:
driver = webdriver.Chrome()
driver.get("https://www.flipkart.com/")

time.sleep(5)

try:
    driver.find_element(By.XPATH,'//button[@class="_2KpZ6l _2doB4z"]').click()
except:
    print("No pop-up")

time.sleep(3)

Designation = driver.find_element(By.CLASS_NAME,"_3704LK")
Designation.send_keys('sneakers')

time.sleep(1)

Search = driver.find_element(By.XPATH,'//button[@class="L0Z3Pu"]')
Search.click()

time.sleep(3)

brand=[]
product_description=[]
price=[]
for page in range(0,3):
    brand_tags = driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    for i in brand_tags[0:100]:
        b=i.text
        brand.append(b)
    product_tags = driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    for i in product_tags[0:100]:
        p=i.text
        product_description.append(p)
        
    price_tags = driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    for i in price_tags[0:100]:
        pr=i.text
        price.append(pr)
        
time.sleep(3)
nextpage = driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
nextpage.click()


df = pd.DataFrame({'Brand': brand[0:100], 'Product Description': product_description[0:100],'Price': price[0:100]})
df

         Brand                                Product Description Price
0        BIRDE      Combo Pack of 2 Casual Shoes Sneakers For Men  ₹479
1        Zixer  Men's Streetwear Pro Style High Top Platform F...  ₹753
2     Magnolia  Modern Trendy Sneakers boot Sneakers Sneakers ...  ₹499
3       BRUTON               Modern Trendy Shoes Sneakers For Men  ₹299
4         aadi  Lightweight,Comfort,Summer,Trendy,Walking,Outd...  ₹389
..         ...                                                ...   ...
95    LE GREEM      Combo Pack of 2 Casual Shoes Sneakers For Men  ₹549
96       BIRDE  Combo Of 2 Leather Shoes FK-310 and FK-Alpha P...  ₹479
97       BIRDE  Combo Pack Of 4 Casual Shoes Loafer Shoes Snea...  ₹479
98  Free Kicks                                   Sneakers For Men  ₹999
99      BRUTON  Junior Zero1 Sports shoes for Men | Gym Traini...  ₹499

[100 rows x 3 columns]

# Q7: Go to webpage https://www.amazon.in/ Enter “Laptop” in the search field and then click the search icon.
You have to scrape 3 attributes for each laptop:
1. Title
2. Ratings
3. Price

In [112]:
driver = webdriver.Chrome()
driver.get("https://www.amazon.in/")

time.sleep(2)

Designation = driver.find_element(By.XPATH,'//input[@class="nav-input nav-progressive-attribute"]')
Designation.send_keys('Laptop')

time.sleep(2)

Search = driver.find_element(By.XPATH,'//span[@class="nav-search-submit-text nav-sprite nav-progressive-attribute"]')
Search.click()

time.sleep(2)

driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[7]/span[10]/li/span/a/span').click()

time.sleep(3)

title=[]
rating=[]
price=[]

title_tags = driver.find_elements(By.XPATH,'//span[@class="a-size-medium a-color-base a-text-normal"]')
for i in title_tags[0:10]:
    b=i.text
    title.append(b)
try:
    rating_tags = driver.find_elements(By.XPATH,'//span[@class="a-icon-alt"]')
    for i in rating_tags[0:10]:
        p=i.text
        rating.append(p)
except:
    rating.append('NAN')
        
price_tags = driver.find_elements(By.XPATH,'//span[@class="a-price-whole"]')
for i in price_tags[0:10]:
    pr=i.text
    price.append(pr)


df = pd.DataFrame({'Title': title[0:10], 'Rating': rating[0:10],'Price': price[0:10]})
df

                                               Title Rating   Price
0  Lenovo IdeaPad Slim 3 Chromebook Intel Celeron...         18,990
1  HP Laptop 15s, Intel Celeron N4500, 15.6 inch(...         30,490
2  Lenovo V15 Intel Celeron N4500 15.6" (39.62 cm...         23,399
3  HP Chromebook 15a Intel Celeron N4500 15.6inch...         23,990
4  ASUS VivoBook 15 (2021), 15.6-inch (39.62 cm) ...         24,990
5  Lenovo V15 Intel Celeron N4500 15.6" (39.62 cm...         23,390
6  AXL Laptop (Vayu Book) Newly Launched Thin & L...         19,990
7  HP Chromebook x360 Intel Celeron N4120 14 inch...         22,990
8  Lenovo IdeaPad 1 Intel Core Celeron N4020 14" ...         25,190
9  AXL VayuBook Laptop 14.1 Inch FHD IPS Display ...         16,990

# Q8: Write a python program to scrape data for Top 1000 Quotes of All Time.
scrap 
a) Quote 
b) Author 
c) Type Of Quotes

In [72]:
driver = webdriver.Chrome()
driver.get("https://www.azquotes.com/")

time.sleep(2)

driver.find_element(By.XPATH,'//a[@href="/top_quotes.html"]').click()
time.sleep(2)

quote=[]
author=[]
type_quote=[]

for page in range(0,10):
    
    quote_tags = driver.find_elements(By.XPATH,'//a[@class="title"]')
    for i in quote_tags[0:1000]:
        b=i.text
        quote.append(b)
    
    author_tags = driver.find_elements(By.XPATH,'//div[@class="author"]')
    for i in author_tags[0:1000]:
        p=i.text
        author.append(p)
        
    
    type_quote_tags = driver.find_elements(By.XPATH,'//div[@class="tags"]')
    for i in type_quote_tags[0:1000]:
        pr=i.text
        type_quote.append(pr)
        
time.sleep(3)
nextpage = driver.find_element(By.XPATH,'//li[@class="next"]')
nextpage.click()

df = pd.DataFrame({'Quote': quote, 'Author': author,'Type Quote': type_quote})
df

,Quote,Author,Type Quote
0,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
1,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
2,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
3,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
4,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
...,...,...,...
995,"When the going gets weird, the weird turn pro.",Hunter S. Thompson,"Music, Sports, Hunting"
996,When a train goes through a tunnel and it gets...,Corrie Ten Boom,"Trust, Encouraging, Uplifting"
997,If you think you are too small to make a diffe...,Dalai Lama,"Inspirational, Funny, Change"
998,"God doesn't require us to succeed, he only req...",Mother Teresa,"Success, God, Mother"
999,Change your thoughts and you change your world.,Norman Vincent Peale,"Inspirational, Motivational, Change"

# Q9: Write a python program to display list of respected former Prime Ministers of India(i.e. Name, Born-Dead, Term of office, Remarks) from https://www.jagranjosh.com/.

In [122]:
driver = webdriver.Chrome()
driver.get("https://www.jagranjosh.com/")

time.sleep(2)

driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div/div[1]/div/div[5]/div/div[1]/header/div[3]/ul/li[3]/a').click()
time.sleep(100)

driver.find_element(By.XPATH,'//*[text()="List of all Prime Ministers of India"]').click()

ElementClickInterceptedException: Message: element click intercepted: Element <a href="https://www.jagranjosh.com/general-knowledge/list-of-all-prime-ministers-of-india-1473165149-1">...</a> is not clickable at point (754, 503). Other element would receive the click: <div style="" id="gdprbx">...</div>
  (Session info: chrome=115.0.5790.102)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00CAA813+48355]
	(No symbol) [0x00C3C4B1]
	(No symbol) [0x00B45358]
	(No symbol) [0x00B75062]
	(No symbol) [0x00B73B98]
	(No symbol) [0x00B7239B]
	(No symbol) [0x00B7179E]
	(No symbol) [0x00B69F5C]
	(No symbol) [0x00B8A73C]
	(No symbol) [0x00B69A36]
	(No symbol) [0x00B8AA94]
	(No symbol) [0x00B9C922]
	(No symbol) [0x00B8A536]
	(No symbol) [0x00B682DC]
	(No symbol) [0x00B693DD]
	GetHandleVerifier [0x00F0AABD+2539405]
	GetHandleVerifier [0x00F4A78F+2800735]
	GetHandleVerifier [0x00F4456C+2775612]
	GetHandleVerifier [0x00D351E0+616112]
	(No symbol) [0x00C45F8C]
	(No symbol) [0x00C42328]
	(No symbol) [0x00C4240B]
	(No symbol) [0x00C34FF7]
	BaseThreadInitThunk [0x76517D59+25]
	RtlInitializeExceptionChain [0x7732B79B+107]
	RtlClearBits [0x7732B71F+191]

# Q10: Write a python program to display list of 50 Most expensive cars in the world (i.e. Car name and Price) from https://www.motor1.com/

In [127]:
driver = webdriver.Chrome()
driver.get("https://www.motor1.com/")

time.sleep(2)

driver.find_element(By.XPATH,'//input[@class="m1-search-panel-input m1-search-form-text"]').send_keys('50 most expensive cars')
driver.find_element(By.XPATH,'//button[@class="m1-search-panel-button m1-search-form-button-animate icon-search-svg"]').click()

time.sleep(3)

driver.find_element(By.XPATH,'//a[@href="/features/308149/most-expensive-new-cars-ever/"]').click()

time.sleep(2)

car_name=[]
price=[]

car_tags = driver.find_elements(By.XPATH,'//h3[@class="subheader"]')
for i in car_tags:
    b=i.text
    car_name.append(b)
display(len(car_name))
    
    
df = pd.DataFrame({'Car name': car_name})
df

51

                            Car name
0                      De Tomaso P72
1                  Ferrari LaFerrari
2                      Pagani Huayra
3                       McLaren Elva
4                        Czinger 21C
5                      Ferrari Monza
6                 Gordon Murray T.33
7                  Koenigsegg Gemera
8                        Zenvo TSR-S
9                 Hennessey Venom F5
10                   Bentley Bacalar
11     Hispano Suiza Carmen Boulogne
12            Bentley Mulliner Batur
13                      Deus Vayanne
14                       SSC Tuatara
15                       Lotus Evija
16               Aston Martin Vulcan
17                        Delage D12
18                 McLaren Speedtail
19                      Rimac Nevera
20                     Pagani Utopia
21              Pininfarina Battista
22                 Ferrari FXX K Evo
23                Gordon Murray T.50
24              Lamborghini Countach
25          Mercedes-AMG Project One
26               Aston Martin Victor
27       Hennessey Venom F5 Roadster
28                  Koenigsegg Jesko
29             Aston Martin Valkyrie
30         W Motors Lykan Hypersport
31                     McLaren Solus
32         Pagani Huayra Roadster BC
33          Bugatti Chiron Pur Sport
34                  Lamborghini Sian
35                  Koenigsegg CC850
36   Bugatti Chiron Super Sport 300+
37                Lamborghini Veneno
38                    Bugatti Bolide
39                   Bugatti Mistral
40               Pagani Huayra Imola
41                      Bugatti Divo
42               SP Automotive Chaos
43                  Pagani Codalunga
44          Mercedes-Maybach Exelero
45                Bugatti Centodieci
46           Bugatti Chiron Profilée
47              Rolls-Royce Sweptail
48          Bugatti La Voiture Noire
49            Rolls-Royce Boat Tail*
50  Most Expensive Cars In The World