# Write a python program to display all the header tags from wikipedia.org and make data frame.

In [2]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.3.2.post1)
Requirement already satisfied: requests in c:\users\sruthi saji nair\anaconda3\lib\site-packages (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from requests) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from requests) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\sruthi saji nair\anaconda3\lib\site-packages (from requests) (2.0.4)

In [3]:
#importing required libraries
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [65]:
#request the webpage server to get the source code
page= requests.get('https://en.wikipedia.org/wiki/Main_Page')
page

#Scraping the page content
soup = BeautifulSoup(page.content)

#Scraping all the header tags by looping
heading_tag = ['h1','h2','h3','h4','h5','h6']
header=[]
for i in soup.find_all(heading_tag):
    header.append(i.text)
#display(header)

# making Dataframe
df = pd.DataFrame({"Header " : header})
df

                         Header
0                      Main Page
1           Welcome to Wikipedia
2  From today's featured article
3               Did you know ...
4                    In the news
5                    On this day
6       Today's featured picture
7       Other areas of Wikipedia
8    Wikipedia's sister projects
9            Wikipedia languages

# Write a python program to display list of respected former presidents of India(i.e. Name , Term ofoffice) from https://presidentofindia.nic.in/former-presidents.htm and make data frame.

In [66]:
page= requests.get('https://presidentofindia.nic.in/former-presidents.htm')
page

#Scraping the page content
soup = BeautifulSoup(page.content)

#Scraping all the name by looping
heading_tag = ['h3']
h3_tag=[]
names=[]
for i in soup.find_all(heading_tag):
    h3_tag.append(i.text)
    names = [j.split('(',1)[0] for j in h3_tag]
#display(names)

#Scraping term of office

term_of_office=[]
for i in soup.find_all('p', class_=""):
    term_of_office.append(i.text.split(":")[1])
for i in sorted([1,3,5,7],reverse=True):
    del term_of_office[i]
#display(term_of_office)

# making Dataframe
df = pd.DataFrame({"Names " : names, "Term of office ": term_of_office})
df

,Names,Term of office
0,Shri Ram Nath Kovind,"25 July, 2017 to 25 July, 2022"
1,Shri Pranab Mukherjee,"25 July, 2012 to 25 July, 2017"
2,Smt Pratibha Devisingh Patil,"25 July, 2007 to 25 July, 2012"
3,DR. A.P.J. Abdul Kalam,"25 July, 2002 to 25 July, 2007"
4,Shri K. R. Narayanan,"25 July, 1997 to 25 July, 2002"
5,Dr Shankar Dayal Sharma,"25 July, 1992 to 25 July, 1997"
6,Shri R Venkataraman,"25 July, 1987 to 25 July, 1992"
7,Giani Zail Singh,"25 July, 1982 to 25 July, 1987"
8,Shri Neelam Sanjiva Reddy,"25 July, 1977 to 25 July, 1982"
9,Dr. Fakhruddin Ali Ahmed,"24 August, 1974 to 11 February, 1977"
10,Shri Varahagiri Venkata Giri,"3 May, 1969 to 20 July, 1969 and 24 August, 1..."
11,Dr. Zakir Husain,"13 May, 1967 to 3 May, 1969"
12,Dr. Sarvepalli Radhakrishnan,"13 May, 1962 to 13 May, 1967"
13,Dr. Rajendra Prasad,"26 January, 1950 to 13 May, 1962"

# Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape and make data frame
a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
b) Top 10 ODI Batsmen along with the records of their team and rating.
c) Top 10 ODI bowlers along with the records of their team and rating

In [67]:
#a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
page= requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
page
#Scraping the page content
soup = BeautifulSoup(page.content)

team=[]
for i in soup.find_all('span', class_="u-hide-phablet"):
    team.append(i.text)
#display(team[0:10])

matches=[]
for i in soup.find_all('td', class_="rankings-block__banner--matches"):
    matches.append(i.text)
for i in soup.find_all('tr',class_="table-body"):
    matches.append(i.text.replace('\n'," ").replace('NZ',"").replace('SA',"").replace('WI',"").replace('SL',"").strip().split()[3])
#display(matches[0:10])

points=[]
for i in soup.find_all('td', class_="rankings-block__banner--points"):
    points.append(i.text)
for i in soup.find_all('tr',class_="table-body"):
    points.append(i.text.replace('\n'," ").replace('NZ',"").replace('SA',"").replace('WI',"").replace('SL',"").strip().split()[4])
#display(points[0:10])

ratings=[]
for i in soup.find_all('td', class_="rankings-block__banner--rating u-text-right"):
    ratings.append(i.text.strip())
for i in soup.find_all('tr',class_="table-body"):
    ratings.append(i.text.replace('\n'," ").replace('NZ',"").replace('SA',"").replace('WI',"").replace('SL',"").strip().split()[5])
#display(ratings[0:10])

df = pd.DataFrame({"Team " : team[0:10], "Matches ": matches[0:10],"Points ": points[0:10], "Ratings ": ratings[0:10]})
df

          Team  Matches  Points  Ratings
0     Australia       23   2,714      118
1      Pakistan       20   2,316      116
2         India       33   3,807      115
3   New Zealand       27   2,806      104
4       England       24   2,426      101
5  South Africa       19   1,910      101
6    Bangladesh       25   2,451       98
7     Sri Lanka       28   2,378       85
8   Afghanistan       13   1,067       82
9   West Indies       32   2,201       69

In [39]:
#b) Top 10 ODI Batsmen along with the records of their team and rating.
page= requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi')
page
#Scraping the page content
soup = BeautifulSoup(page.content)

bRating=[]
for i in soup.find('div',class_="rankings-block__banner--rating"):
    bRating.append(i.text)

for i in soup.find_all('td',class_="table-body__cell u-text-right rating"):
    bRating.append(i.text)

bTeam=[]
bTeam.append('PAK')
for i in soup.find_all('span',class_="table-body__logo-text"):
    bTeam.append(i.text)

df=pd.DataFrame.from_dict({'Team':bTeam[0:10],'Rating':bRating[0:10]},orient='index')
odiBatsMen=df.transpose()
odiBatsMen

  Team Rating
0  PAK    886
1   SA    777
2  PAK    755
3  PAK    745
4  IND    738
5  IRE    726
6  AUS    726
7  IND    719
8   SA    718
9  IND    707

In [68]:
#c) Top 10 ODI bowlers along with the records of their team and rating
page= requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling')
page
#Scraping the page content
soup = BeautifulSoup(page.content)

BowlRating=[]
for i in soup.find('div',class_="rankings-block__banner--rating"):
    BowlRating.append(i.text)

for i in soup.find_all('td',class_="table-body__cell rating"):
    BowlRating.append(i.text)

BowlTeam=[]
for i in soup.find_all('div',class_="rankings-block__banner--nationality"):
    BowlTeam.append(i.text.strip())
        
for i in soup.find_all('span',class_="table-body__logo-text"):
    BowlTeam.append(i.text)
    
df=pd.DataFrame.from_dict({'Team':BowlTeam[0:10],'Rating':BowlRating[0:10]},orient='index')
odiBowlMen=df.transpose()
odiBowlMen

  Team Rating
0  AUS    705
1  IND    691
2  AUS    686
3   NZ    667
4   NZ    660
5  AUS    652
6  AFG    640
7  PAK    630
8  AFG    630
9  AFG    626

# Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape and make data frame
a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.
b) Top 10 women’s ODI Batting players along with the records of their team and rating.
c) Top 10 women’s ODI all-rounder along with the records of their team and rating.

In [64]:
#a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.
page= requests.get('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')
page
#Scraping the page content
soup = BeautifulSoup(page.content)

team=[]
for i in soup.find_all('span', class_="u-hide-phablet"):
    team.append(i.text)
#display(team[0:10])

matches=[]
for i in soup.find_all('td', class_="rankings-block__banner--matches"):
    matches.append(i.text)
for i in soup.find_all('tr',class_="table-body"):
    matches.append(i.text.replace('\n'," ").replace('NZ',"").replace('SA',"").replace('WI',"").replace('SL',"").strip().split()[3])
#display(matches[0:10])

points=[]
for i in soup.find_all('td', class_="rankings-block__banner--points"):
    points.append(i.text)
for i in soup.find_all('tr',class_="table-body"):
    points.append(i.text.strip().split()[4])
#display(points[0:10])

ratings=[]
for i in soup.find_all('td', class_="rankings-block__banner--rating u-text-right"):
    ratings.append(i.text.strip())
for i in soup.find_all('tr',class_="table-body"):
    ratings.append(i.text.strip().split()[5])
#display(ratings[0:10])

df = pd.DataFrame({"Team " : team[0:10], "Matches ": matches[0:10],"Points ": points[0:10], "Ratings ": ratings[0:10]})
df

          Team  Matches  Points  Ratings
0     Australia       21   3,603      172
1       England       28   3,342      119
2  South Africa       26      26    3,098
3         India       27   2,820      104
4   New Zealand       28      28    2,688
5   West Indies       29      29    2,743
6    Bangladesh       14     977       70
7     Sri Lanka       12      12      820
8      Thailand       12     806       67
9      Pakistan       27   1,678       62

In [50]:
#b) Top 10 women’s ODI Batting players along with the records of their team and rating.
page= requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi')
page
#Scraping the page content
soup = BeautifulSoup(page.content)

WRating=[]
for i in soup.find('div',class_="rankings-block__banner--rating"):
    WRating.append(i.text)

for i in soup.find_all('td',class_="table-body__cell u-text-right rating"):
    WRating.append(i.text)

WTeam=[]
WTeam.append('SL')
for i in soup.find_all('span',class_="table-body__logo-text"):
    WTeam.append(i.text)

df=pd.DataFrame.from_dict({'Team':WTeam[0:10],'Rating':WRating[0:10]},orient='index')
odiBatsWomen=df.transpose()
odiBatsWomen

  Team Rating
0   SL    758
1  AUS    754
2   SA    732
3  ENG    731
4  AUS    717
5  IND    716
6  IND    714
7  AUS    626
8   WI    618
9  ENG    595

In [51]:
#c) Top 10 women’s ODI all-rounder along with the records of their team and rating.
page= requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')
page
#Scraping the page content
soup = BeautifulSoup(page.content)

AllRounderRating=[]
for i in soup.find('div',class_="rankings-block__banner--rating"):
    AllRounderRating.append(i.text)

for i in soup.find_all('td',class_="table-body__cell rating"):
    AllRounderRating.append(i.text)

AllRounderTeam=[]
for i in soup.find_all('div',class_="rankings-block__banner--nationality"):
    AllRounderTeam.append(i.text.strip())
        
for i in soup.find_all('span',class_="table-body__logo-text"):
    AllRounderTeam.append(i.text)
    
df=pd.DataFrame.from_dict({'Team':AllRounderTeam[0:10],'Rating':AllRounderRating[0:10]},orient='index')
AllRounderWomen=df.transpose()
AllRounderWomen

  Team Rating
0   WI    382
1  ENG    371
2  AUS    366
3   SA    349
4   NZ    328
5  IND    322
6  AUS    292
7  AUS    250
8   NZ    233
9  PAK    232

# Write a python program to scrape mentioned news details from https://www.cnbc.com/world/?region=world and
make data frame
i) Headline
ii) Time
iii) News Link

In [63]:

page= requests.get('https://www.cnbc.com/world/?region=world')
page
#Scraping the page content
soup = BeautifulSoup(page.content)

# Headline
Headline=[]
for i in soup.find_all('div',class_="LatestNews-headlineWrapper"):
    Headline.append(i.text.split("Ago")[1])
#display(Headline)

# Time   
Time=[]    
for i in soup.find_all('time',class_="LatestNews-timestamp"):
    Time.append(i.text)
#display(Time)

# NewsLink
NewsLink=[]
for i in soup.find_all('a',class_="LatestNews-headline"):
    NewsLink.append(i["href"])
#display(NewsLink)

df=pd.DataFrame({"Headline ": Headline, "Time ": Time ,"NewsLink ": NewsLink})
df

,Headline,Time,NewsLink
0,Piper Sandler says Coinbase can fall 25% as re...,18 Min Ago,https://www.cnbc.com/2023/07/05/piper-sandler-...
1,Jefferies says this car rental player’s shares...,27 Min Ago,https://www.cnbc.com/2023/07/05/jefferies-says...
2,Stocks making the biggest moves in the premark...,30 Min Ago,https://www.cnbc.com/2023/07/05/stocks-making-...
3,World registers hottest day since records bega...,32 Min Ago,https://www.cnbc.com/2023/07/05/climate-crisis...
4,Saudi energy minister says latest Riyadh-Mosco...,49 Min Ago,https://www.cnbc.com/2023/07/05/saudi-energy-m...
5,Citi says this offshore drilling stock can soa...,1 Hour Ago,https://www.cnbc.com/2023/07/05/citi-says-this...
6,5 things to know before the stock market opens...,1 Hour Ago,https://www.cnbc.com/2023/07/05/5-things-to-kn...
7,"Major League Pickleball names new CEO, COO to ...",1 Hour Ago,https://www.cnbc.com/2023/07/05/major-league-p...
8,Goldman upgrades Netflix as streaming giant re...,3 Hours Ago,https://www.cnbc.com/2023/07/05/goldman-upgrad...
9,China unexpectedly cancels top EU diplomat's B...,3 Hours Ago,https://www.cnbc.com/2023/07/05/china-unexpect...
10,Turkey's inflation rate cools despite steep li...,4 Hours Ago,https://www.cnbc.com/2023/07/05/turkeys-inflat...
11,2-year Treasury yield dips as investors await ...,4 Hours Ago,https://www.cnbc.com/2023/07/05/us-treasury-yi...
12,Zelenskyy warns of provocations at nuclear pla...,5 Hours Ago,https://www.cnbc.com/2023/07/05/ukraine-war-li...
13,Australia and Indonesia have signed a 'win-win...,5 Hours Ago,https://www.cnbc.com/2023/07/05/australia-and-...
14,CNBC Daily Open: A new dawn for Japan,6 Hours Ago,https://www.cnbc.com/2023/07/05/stock-markets-...
15,Europe stocks lower as economic gloom returns;...,7 Hours Ago,https://www.cnbc.com/2023/07/05/european-marke...
16,Millions of workers face up to challenge of he...,7 Hours Ago,https://www.cnbc.com/2023/07/05/as-planet-heat...
17,K-pop stocks dip briefly on report of antitrus...,8 Hours Ago,https://www.cnbc.com/2023/07/05/k-pop-stocks-h...
18,Goldman Sachs says AI will 'super-charge' musi...,10 Hours Ago,https://www.cnbc.com/2023/07/05/goldman-sachs-...
19,$19 billion in trade stranded as Canada's port...,11 Hours Ago,https://www.cnbc.com/2023/07/05/canadas-port-l...
20,Here are 4 tips on surviving long job intervie...,12 Hours Ago,https://www.cnbc.com/2023/07/05/4-tips-on-surv...
21,CNBC Daily Open: The sun rises on Japan,12 Hours Ago,https://www.cnbc.com/2023/07/05/stock-markets-...
22,"Ed Yardeni ups growth forecasts, says a unique...",12 Hours Ago,https://www.cnbc.com/2023/07/05/ed-yardeni-upg...
23,Goldman's list of top picks to buy right now i...,13 Hours Ago,https://www.cnbc.com/2023/07/05/baba-and-more-...
24,Japanese stocks peaked in 1989. One strategist...,13 Hours Ago,https://www.cnbc.com/2023/07/05/japans-nikkei-...
25,Asia markets fall as investors digest private ...,13 Hours Ago,https://www.cnbc.com/2023/07/05/asia-markets.html
26,Stock futures fall as investors await Fed meet...,14 Hours Ago,https://www.cnbc.com/2023/07/04/stock-market-t...
27,Biden urges stricter gun control after spate o...,16 Hours Ago,https://www.cnbc.com/2023/07/04/biden-urges-st...
28,Twitter says rate limits were to help thwart b...,18 Hours Ago,https://www.cnbc.com/2023/07/04/twitter-says-r...
29,Airlines struggled ahead of July Fourth weeken...,20 Hours Ago,https://www.cnbc.com/2023/07/04/why-airline-st...

# Write a python program to scrape the details of most downloaded articles from AI in last 90days.
https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles
Scrape below mentioned details and make data frame
i) Paper Title
ii) Authors
iii) Published Date
iv) Paper URL

In [84]:
page= requests.get('https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles')
page
#Scraping the page content
soup = BeautifulSoup(page.content)


#Paper Title
PaperTitle=[]
for i in soup.find_all('h2',class_="sc-1qrq3sd-1 gRGSUS sc-1nmom32-0 sc-1nmom32-1 btcbYu goSKRg"):
    PaperTitle.append(i.text)
#display(PaperTitle)

#Authors
Authors=[]
for i in soup.find_all('span',class_="sc-1w3fpd7-0 dnCnAO"):
    Authors.append(i.text)
#display(Authors)

#Published Date
PublishedDate=[]
for i in soup.find_all('span',class_="sc-1thf9ly-2 dvggWt"):
    PublishedDate.append(i.text)
#display(PublishedDate)

#Paper URL
PaperURL=[]
for i in soup.find_all('a',class_="sc-5smygv-0 fIXTHm"):
    PaperURL.append(i['href'])
#display(PaperURL)

df=pd.DataFrame({"Paper Title ": PaperTitle, "Authors ": Authors ,"Published Date ": PublishedDate,"Paper URL ": PaperURL})
df

,Paper Title,Authors,Published Date,Paper URL
0,Reward is enough,"David Silver, Satinder Singh, Doina Precup, Ri...",October 2021,https://www.sciencedirect.com/science/article/...
1,Explanation in artificial intelligence: Insigh...,Tim Miller,February 2019,https://www.sciencedirect.com/science/article/...
2,Creativity and artificial intelligence,Margaret A. Boden,August 1998,https://www.sciencedirect.com/science/article/...
3,Conflict-based search for optimal multi-agent ...,"Guni Sharon, Roni Stern, Ariel Felner, Nathan ...",February 2015,https://www.sciencedirect.com/science/article/...
4,Knowledge graphs as tools for explainable mach...,"Ilaria Tiddi, Stefan Schlobach",January 2022,https://www.sciencedirect.com/science/article/...
5,Law and logic: A review from an argumentation ...,"Henry Prakken, Giovanni Sartor",October 2015,https://www.sciencedirect.com/science/article/...
6,Between MDPs and semi-MDPs: A framework for te...,"Richard S. Sutton, Doina Precup, Satinder Singh",August 1999,https://www.sciencedirect.com/science/article/...
7,Explaining individual predictions when feature...,"Kjersti Aas, Martin Jullum, Anders Løland",September 2021,https://www.sciencedirect.com/science/article/...
8,Multiple object tracking: A literature review,"Wenhan Luo, Junliang Xing and 4 more",April 2021,https://www.sciencedirect.com/science/article/...
9,A survey of inverse reinforcement learning: Ch...,"Saurabh Arora, Prashant Doshi",August 2021,https://www.sciencedirect.com/science/article/...
10,Evaluating XAI: A comparison of rule-based and...,"Jasper van der Waa, Elisabeth Nieuwburg, Anita...",February 2021,https://www.sciencedirect.com/science/article/...
11,Explainable AI tools for legal reasoning about...,"Joe Collenette, Katie Atkinson, Trevor Bench-C...",April 2023,https://www.sciencedirect.com/science/article/...
12,Hard choices in artificial intelligence,"Roel Dobbe, Thomas Krendl Gilbert, Yonatan Mintz",November 2021,https://www.sciencedirect.com/science/article/...
13,Assessing the communication gap between AI mod...,"Oskar Wysocki, Jessica Katharine Davies and 5 ...",March 2023,https://www.sciencedirect.com/science/article/...
14,Explaining black-box classifiers using post-ho...,"Eoin M. Kenny, Courtney Ford, Molly Quinn, Mar...",May 2021,https://www.sciencedirect.com/science/article/...
15,The Hanabi challenge: A new frontier for AI re...,"Nolan Bard, Jakob N. Foerster and 13 more",March 2020,https://www.sciencedirect.com/science/article/...
16,Wrappers for feature subset selection,"Ron Kohavi, George H. John",December 1997,https://www.sciencedirect.com/science/article/...
17,Artificial cognition for social human–robot in...,"Séverin Lemaignan, Mathieu Warnier and 3 more",June 2017,https://www.sciencedirect.com/science/article/...
18,A review of possible effects of cognitive bias...,"Tomáš Kliegr, Štěpán Bahník, Johannes Fürnkranz",June 2021,https://www.sciencedirect.com/science/article/...
19,The multifaceted impact of Ada Lovelace in the...,Luigia Carlucci Aiello,June 2016,https://www.sciencedirect.com/science/article/...
20,Robot ethics: Mapping the issues for a mechani...,"Patrick Lin, Keith Abney, George Bekey",April 2011,https://www.sciencedirect.com/science/article/...
21,Reward (Mis)design for autonomous driving,"W. Bradley Knox, Alessandro Allievi and 3 more",March 2023,https://www.sciencedirect.com/science/article/...
22,Planning and acting in partially observable st...,"Leslie Pack Kaelbling, Michael L. Littman, Ant...",May 1998,https://www.sciencedirect.com/science/article/...
23,What do we want from Explainable Artificial In...,"Markus Langer, Daniel Oster and 6 more",July 2021,https://www.sciencedirect.com/science/article/...

# Write a python program to scrape mentioned details from dineout.co.inand make data frame
i) Restaurant name
ii) Cuisine
iii) Location
iv) Ratings
v) Image UR

In [94]:
page= requests.get('https://www.dineout.co.in/delhi-restaurants/buffet-special')
page
#Scraping the page content
soup = BeautifulSoup(page.content)

#Restaurant name
Restaurantname=[]
for i in soup.find_all('div',class_="restnt-info cursor"):
    Restaurantname.append(i.text)
#display(Restaurantname)

#Cuisine
Cuisine=[]
for i in soup.find_all('span',class_="double-line-ellipsis"):
    Cuisine.append(i.text.split("|")[1])
#display(Cuisine)

#Location
Location=[]
for i in soup.find_all('div',class_="restnt-loc ellipsis"):
    Location.append(i.text)
#display(Location)

#Ratings
Ratings=[]
for i in soup.find_all('div',class_="restnt-rating rating-4"):
    Ratings.append(i.text)
#display(Ratings)

#Image URL
ImageURL=[]
for i in soup.find_all('img',class_="no-img"):
    ImageURL.append(i['data-src'])
#display(ImageURL)


df=pd.DataFrame({"Restaurant Name ": Restaurantname, "Cuisine ": Cuisine ,"Location ": Location,"Ratings ": Ratings,"ImageURL ":ImageURL})
df

,Restaurant Name,Cuisine,Location,Ratings,ImageURL
0,"Castle BarbequeConnaught Place, Central Delhi","Chinese, North Indian","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
1,"Jungle Jamboree3CS Mall,Lajpat Nagar - 3, Sout...","North Indian, Asian, Italian","3CS Mall,Lajpat Nagar - 3, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
2,"Cafe KnoshThe Leela Ambience Convention Hotel,...","Italian, Continental","The Leela Ambience Convention Hotel,Shahdara, ...",4.3,https://im1.dineout.co.in/images/uploads/resta...
3,"Castle's BarbequePacific Mall,Tagore Garden, W...","Chinese, North Indian","Pacific Mall,Tagore Garden, West Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
4,"The Barbeque CompanyGardens Galleria,Sector 38...","North Indian, Chinese","Gardens Galleria,Sector 38A, Noida",3.9,https://im1.dineout.co.in/images/uploads/resta...
5,"India GrillHilton Garden Inn,Saket, South Delhi","North Indian, Italian","Hilton Garden Inn,Saket, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
6,"Delhi BarbequeTaurus Sarovar Portico,Mahipalpu...",North Indian,"Taurus Sarovar Portico,Mahipalpur, South Delhi",3.7,https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que VillageIndirapuram Ha...,North Indian,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad",3.8,https://im1.dineout.co.in/images/uploads/resta...
8,"Indian Grill RoomSuncity Business Tower,Golf C...","North Indian, Mughlai","Suncity Business Tower,Golf Course Road, Gurgaon",4.3,https://im1.dineout.co.in/images/uploads/resta...